### ISSUE TITLE
WARNING: Communication failure, is the MFRC522 properly connected?

### ISSUE THREAD

**Issue by brettbyrd** [miguelbalboa/rfid#101]
I am new to ARDUINO. I have tried for the past two days to get the MFRC-522 to work with my Arduino UNO. I keep getting this message when I use the Dump Code 

********************
MFRC522 Software Version: 0x0 (unknown)
WARNING: Communication failure, is the MFRC522 properly connected?
********************
I set everything up just like in the sketch. 
Any help is appreciated

**Comment by Rotzbua** [comment]
Does one of the other codes work? Do you use 3.3V? Try the RST to RST of the arduino.

**Comment by danielyc** [comment]
i have the same problem, and tried those 3 things.
i hope there is a solution to this problem

**Comment by mariohinojosa** [comment]
Hi, I am having exactly the same problem.

To give a bit of context. I have been using the RFID-RC522 for a project with a RPi, however when I changed it from a breadboard to a permaproto it stopped reading the cards. I wanted to check if the reader was the problem or the board I created, thus, I decided to test the reader on my Arduino Uno. I followed every step mentioned in the Readme file and in other YT videos but I am getting the aforementioned warning.

Could it be that the reader is very fragile and prone to breaking?

**Comment by ccreutzig** [comment]
Did you ever link the reader directly to the Arduino? If so, you may have fried the inputs with your 5V levels. Not all 3.3V equipment tolerates getting 5V, even for a short time.

**Comment by KiKiZ59** [comment]
Hi,
I've got the exact same problem. I verified my wiring 20 times, i connect the arduino to 3.3V.
I tried with UNO and MEGA and with two different RFID reader.
I always have this warning : 

MFRC522 Software Version: 0x0 (unknown)
WARNING: Communication failure, is the MFRC522 properly connected?

I added these lines just below mfrc522.PCD_Init();	

        Serial.print("MFRC522 software version = ");
        Serial.println(mfrc522.PCD_ReadRegister(mfrc522.VersionReg),HEX);

And this returns 0.

Can anyone help me please? I'm getting mad with that problem.
I use an arduino clone bought in China that use ch340g driver.
Does the library work with that clone?
Thanks,
Kikiz

**Comment by danielyc** [comment]
soldering the pins fixed the problem for me

**Comment by Tarino01** [comment]
I had exactly the same problem and the reason was that the connection of MOSI and MISO was reverse!
I used a pdf file from internet to determine the pinout of Arduino pro mini (3.3V, 8MHz). However, there was an error in that pdf file about MISO and MOSI pins. It is better to check your pins once again.

**Comment by DoctorRu** [comment]
Remember to change code from default REST_PIN 9 and SS_PIN 10 to 5 and 53 if you are using in Mega 2560.

<code>
#define RST_PIN		5		</code>
<code>
#define SS_PIN		53	</code>

**Comment by antararay19** [comment]
It could be a connection issue. In my case after fixing on the breadboard properly , when the red LED glowed consistently, the issue went away and version came

**Comment by KiKiZ59** [comment]
I'd like to thank all of you for your responses.
I fixed the problem soldering the pins instead of using a breadboard.
kikiz

**Comment by sarge8306** [comment]
Thank you for the suggestion to solder the pins....I finally got this thing to work now :).  I also wanted to thank the suggestion to increase the baud rate, I've tried tinkering with another project that had a slow response to no avail and was beginning to doubt my logic, but this reinforced it...thank you again!

**Comment by TahasinAveins** [comment]
MFRC522 Software Version: 0x0 (unknown)
WARNING: Communication failure, is the MFRC522 properly connected?
 how can i config 
#define RST_PIN         9          // Configurable, see typical pin layout above
#define SS_PIN          10         // Configurable, see typical pin layout above


please help me

**Comment by surabhi96** [comment]
@TahasinAveins check out the response by @DoctorRu in case you are using arduino mega. If you're using arduino uno you don't have to change the config.

**Comment by sai-suresh** [comment]
soldering the pins will fix the problem.

**Comment by brucesaints** [comment]
resold the pins fixed the problem for me too

**Comment by sobinsunny111** [comment]
I used RFID-RC522 with Arduino UNO. I had the same issues but could not find any solution despite searching number of forums, videos and sites.

Finally, I resolved the issue by these steps:
    1. Make sure that you have installed the RFID library.
    2. If not installed, go to Sketch - Include library - Manage libraries - Search for RFID in the search box and install MFRC522 Library.
    3. If the RFID still dont work, then go back to the same step 2 and this time you might see an option for 'Update'.
    4. Do step 3 twice or thrice if required.
    5. Now go to Examples - MFRC522 - DumpInfo and upload it. Check the serial monitor. Your issue might get resolved as mine was okay by following this steps.

**Comment by TahasinAveins** [comment]
Thanks for your reply..
But I have solved the problem.. It was loss connection

**Comment by 21700965** [comment]
How did you solve the problem without soldering the pins?

**Comment by TahasinAveins** [comment]
No no, I have done my soldering..

**Comment by YapWC** [comment]
Probably is the connection problem just change new wire or maybe just solder it up. This will solve the problem.

**Comment by TahasinAveins** [comment]
Yep right

**Comment by fab97419** [comment]
Hello everyone,
I'm sorry for the way I'm going to write, because I speak bad English I'm from France.
Regarding the communication error of the RIFD RC522 module, I had exactly the same problem and I just solved it by soldering the wires.
here I hope this will help you :)

**Comment by mathiasconradt** [comment]
Confirmed, soldering the pins fixed it work me as well.

**Comment by douglasdeodato** [comment]
2020 update  - Confirmed, soldering the pins fixed it for me as well.

I tried without solder and did not work, so I have to solder.

**Comment by Kusiimwa** [comment]
> I used RFID-RC522 with Arduino UNO. I had the same issues but could not find any solution despite searching number of forums, videos and sites.
> 
> Finally, I resolved the issue by these steps:
> 1. Make sure that you have installed the RFID library.
> 2. If not installed, go to Sketch - Include library - Manage libraries - Search for RFID in the search box and install MFRC522 Library.
> 3. If the RFID still dont work, then go back to the same step 2 and this time you might see an option for 'Update'.
> 4. Do step 3 twice or thrice if required.
> 5. Now go to Examples - MFRC522 - DumpInfo and upload it. Check the serial monitor. Your issue might get resolved as mine was okay by following this steps.

This has worked for me. Thank you!

**Comment by Nisanth95** [comment]
I tried with jumper wires, but I still get the warning. 
Do I still have to buy new wires although my RFID-RC522 lights up when connected? 
Is there another solution than soldering? I need a breadboard to connect the arduino and RFID to a nodeMCU.
Thanks in advance

**Comment by starfield33** [comment]
Reverse your communication cable - often when they’re around the wrong way they bring this error up. 

 
Very Best Regards, | 
Mit freundlichen Grüßen
Graham Andrews

***@***.***
***@***.***
‭‭+‭44 7787 133043‬ Mobile - London

**Comment by Nisanth95** [comment]
I somehow made it work, but when I take my card og tag, it will not register. 
Although the warning line is gone, the firmware version is unknown. 
It says 
"?Firmware Version: 0xF8 = (unknown)
Scan PICC to see UID, SAK, type, and data blocks..."

**Comment by SauravBhosale** [comment]
Guys Check your wires. I had the same problem. Try using new Jumper wires, it solved the problem in my case

**Comment by Nip-pa** [comment]
MISO   >>>   D6
MOSI   >>>   D7

#define RST_PIN        D3        
#define SS_PIN          D4

**Comment by AazWar-Tech** [comment]
Lo que a mi me funciono , es que precisamente no estaba del todo conectado, es decir que  si coloco el lector en la protoboard o lo dejo conectado en los pines pero sin soldar en el lector marcara la advertencia, pero si hago presión para que los pines toquen bien el circuito del lector entonces se quita el warning y funciona correctamente.

**Comment by vashist22** [comment]
check the baud rate,set it to 115200

**Comment by kariuki51jane** [comment]
Am experiencing this problem with my RFID-RC522, any one to help me out

WARNING: Communication failure, is the MFRC522 properly connected?
Scan PICC to see UID, SAK, type, and data blocks...
��@&4��p0� = (unknown)

**Comment by RaduMinecraft** [comment]
On my genuine arduino doesn't work but on arduino clone works perfectly, why?

**Comment by kyle-yeh** [comment]
It may be that the voltage is too low due to poor contact. I pressed it to make the board more in contact with it.

**Comment by FADELELLAHerrami** [comment]
For me, the issue lies in NOT using the breadboard and soldering the pins of the RFID-RC522. that's the solution

**Comment by PBonvang** [comment]
Had the same problem.

**Specs:**
Board: Elegoo Uno R3 (Arduino Uno replica)
RFID: RFID-RC522

**Solution:**
- Use female to male wires
- Instead of the v3.3 pin use the v_in pin

**Comment by TxMike0038** [comment]
> Had the same problem.
> 
> **Specs:** Board: Elegoo Uno R3 (Arduino Uno replica) RFID: RFID-RC522
> 
> **Solution:**
> 
> * Use female to male wires
> * Instead of the v3.3 pin use the v_in pin

Connecting to the V_in instesad of the 3.3v fixed the issue for me, thank you so much!

**Comment by achrafbjn74** [comment]
if you have a problem of MFRC522 not connected , try soldering places between wires and RC522 , the soldering is well

**Comment by dofan28** [comment]
https://www.youtube.com/watch?v=5ZirOCEJ9AA 

i'm suggestions recommend watch it, it working me

**Comment by Beardsome** [comment]
arduino SPI pins are 5V tolerated then when i connect with RC522 RFID reader is it damaged the RFID reader after few time
