### ISSUE TITLE
RC522 with SD Card reader

### ISSUE THREAD

**Issue by AxissXs** [miguelbalboa/rfid#103]
Hello
I'm new to arduino and such stuffs
trying to attach rc522 and sd card reader to my arduino uno
what can i do with the shared pins?

tnx in advance

**Comment by Rotzbua** [comment]
Hi, this issue tracker is only for issues with the library.
For general questions use arduino forum or something equal.
There are also many tutorials about SPI like http://tronixstuff.com/2011/05/13/tutorial-arduino-and-the-spi-bus/

>  what can i do with the shared pins?

connect to both

Best

**Comment by AxissXs** [comment]
ok, thank you
