### ISSUE TITLE
Missing wipe on magic cards

### ISSUE THREAD

**Issue by ChristopheLorenz** [miguelbalboa/rfid#116]
I'm missing the wipe (reset to default) for the magic chinese cards.
I tried to implement it myself (transmitting 0x41 instead of 0x43 in backdoor) but it doesn't seem to work.
Do you have more information on how to properly do it ?
Maybe my cards are different because they don't respond 0x0A to the backdoor, still the write to block 0 works.

**Comment by Rotzbua** [comment]
@ChristopheLorenz Hi. Did you found a solution? Or a more detailed bug description?
Otherwise I will close this issue.

**Comment by Rotzbua** [comment]
no response -> close
