### ISSUE TITLE
Bords with integrated ethernet

### ISSUE THREAD

**Issue by inu-web** [miguelbalboa/rfid#118]
Hi, I have already successfully used this great library with unos and megas.... 
But now I got an arduino Leonardo ETH with integrated W5500 ethernet and I can not get it to work with the RC522 reader which Works fine with the UNO and the Standard-W5100 ethernetshield for example. 
I also tried another board (http://tronixlabs.com/arduino/boards/ethernet/dfrobot-arduino-compatible-with-onboard-w5500-ethernet-and-poe-australia/) that seems to be somewhat similar. 
Both boards Do Not recognize the RC522 reader during setup. 
Even if I deactivate the CS from ethernet and SD, the reader can not be accessed. 
There must be something general that Blocks the Icsp or so?
I have used the mosi, miso and sck from the 6 pin icsp header of the board because they do not have them on the GPIO Pins like the UNOs or Megas and also tried different Pins as the CS pin for the reader.
No success on getting the reader to respond.
Is there anything else I can try?
Thanks in advance and kind regards 
Gerald

**Comment by mdxs** [comment]
Check #97
