### ISSUE TITLE
How can I use two MFRC522 with one Arduino Mega?

### ISSUE THREAD

**Issue by ViniciusMoscardini** [miguelbalboa/rfid#119]
Please, I don't know how to use two MFRC522 with one Arduino Mega.

I tried to use 2 differents SS, but not work.

Thank you very much.

**Comment by sophiekovalevsky** [comment]
The library have a huge documentation. Actually, in README file there is the PIN layout that you need to use to work properly in Arduino Mega.

SS can be literally any digital output, try to use another one. 

Best regards!

**Comment by miguelbalboa** [comment]
Hi @ViniciusMoscardini  
Also, please check the example [examples/ReadUidMultiReader/ReadUidMultiReader.ino](/miguelbalboa/rfid/blob/master/examples/ReadUidMultiReader/ReadUidMultiReader.ino) by @lmmeng 

Greetings.
