### ISSUE TITLE
Why I can only read the cards by DumpInfo sketch if there are at least 2 cards ?

### ISSUE THREAD

**Issue by saytinh** [miguelbalboa/rfid#121]
Anyone can tell me why I can not read a single Mifare card? Can read the card only if having at least 2 cards side by side. For example: 2 cards could be included first one is a 13.56MHz  and another is whatever like 13.56Mhz or 125Mhz.

Please point out why that? Thanks

**Comment by Rotzbua** [comment]
@saytinh I think it is a hardware issue.
