### ISSUE TITLE
Responded with NAK.

### ISSUE THREAD

**Issue by Bladeslayer1000** [miguelbalboa/rfid#123]
Hello,

Today I received my RFID RC522 module, and I tested my first card and badge that I received with it.

I used the rfid_write_personal_data sketch to write some data to my card. But when I'm trying to write data to it I get the error message: 'MIFARE_Write() failed: A MIFARE PICC responded with NAK.'

I searched around the internet, and didnt find a solution to this problem. Does anyone know a issue to fix this error?

**Comment by Rotzbua** [comment]
May have a look at #84
