### ISSUE TITLE
Support for 125 khz tags

### ISSUE THREAD

**Issue by Gerst20051** [miguelbalboa/rfid#128]
Any way to dump data from any type of RFID card?

**Comment by Rotzbua** [comment]
Please read the readme and data sheet first.
The only way to read 125 kHz tags: replace hardware and library.

Can be closed.

**Comment by Gerst20051** [comment]
Do you know where to find the hardware or library for that?

**Comment by Rotzbua** [comment]
Maybe:
http://www.seeedstudio.com/depot/125Khz-RFID-module-UART-p-171.html
