### ISSUE TITLE
Adafruit Bluefruit LE Micro - Bluetooth Low Energy + ATmega32u4 - Pin Layout

### ISSUE THREAD

**Issue by octave** [miguelbalboa/rfid#139]
Hi,

I was wondering what to do for the pin layout on the Adafruit Bluefruit LE Micro - Bluetooth Low Energy + ATmega32u4: http://www.adafruit.com/products/2661

More info on the pinouts here: https://learn.adafruit.com/bluefruit-le-micro-atmega32u4-microcontroller-usb-bluetooth-le-in-one/pinouts

Should I use the three SPI pins?

Thank you!

**Comment by Rotzbua** [comment]
@octave Hi. Did you found a solution? Or a more detailed bug description?
Otherwise I will close this issue.

**Comment by Rotzbua** [comment]
no response -> close
