### ISSUE TITLE
Software SPI for RFID MRC-522

### ISSUE THREAD

**Issue by abhaysbharadwaj** [miguelbalboa/rfid#148]
I have made some changes and come up with the code to interface the RFID module to any pins of arduino (tested on uno and nano) using Software SPI concept. This is really useful when the arduino's hardware (actual) SPI pins are already used by other sensors/components.
find out more at: https://github.com/abhaysbharadwaj/RFID-MRC522

**Comment by alexandre72** [comment]
Tested, works perfectly here. +1 to add it into current code. Thanks for share!

**Comment by abhaysbharadwaj** [comment]
Great! your welcome!

**Comment by mdxs** [comment]
Can be closed.
