### ISSUE TITLE
RFID using MFRC522 to connect to a database with add and remove

### ISSUE THREAD

**Issue by imon214** [miguelbalboa/rfid#179]
Hi guys, need help, anyone know how to do this?, have arduino mega board and a RC522 reader, want to connect it to a database and make add and delete card/tag.. please help, just new with RFID, Thanks

Really need this, anyone who is knowledgeable, please answer, Thanks

**Comment by Rotzbua** [comment]
Hi, there a tons of stuff already at the internet. Look at http://forum.arduino.cc/ , https://hackaday.io/lists , http://www.instructables.com/

**Comment by mdxs** [comment]
Can be closed, assuming @imon214 followed the good advise and links from @Rotzbua
