### ISSUE TITLE
Interrupt mode instead of pooling

### ISSUE THREAD

**Issue by shayo** [miguelbalboa/rfid#180]
Hi,

Great work on writing this library.
I've been trying to get through the crappy documentation to understand how I can use interrupt mode instead of constant pooling.
Can you help with this? I would like to use this device in low power mode and trigger the host using the IRQ line to wake up once a card was detected.

Thanks,

Shay

**Comment by Rotzbua** [comment]
Duplicate to #92

**Comment by shayo** [comment]
Bummer. I was hoping someone figured this out.

**Comment by uparlayan** [comment]
Any new developments?
