### ISSUE TITLE
getting a UID as a string for sending to Print.serial1(UID.hex) or as Keyboard.print(UID.dec)

### ISSUE THREAD

**Issue by Netoperz** [miguelbalboa/rfid#181]
Hello,

I'm looking for a simple way of getting UID as HEX but without spaces with upper letters and to be able to send them as string.

In actual demo of Dump info the value of UID is coming as byte after byte,
When i use Println before getting the UID i get the bytes one after another, it is hard to manage in my project.

It would be superb. if there would be a separate functions to call just if you need UID as string, both as Decimal or if you need as hex. For both 4byte and 7 byte UID's

For example : "0A5C9F76" not (byte)0A (byte) 5C (byte)9F (byte)76

If there is a way i just can't find it.

**Comment by Rotzbua** [comment]
Hi,
that is not an issue with this library, please use platforms which are specialized in c/c++ problems like http://forum.arduino.cc/ .
Best
