### ISSUE TITLE
Error in PICC_Select() function

### ISSUE THREAD

**Issue by alexmina** [miguelbalboa/rfid#182]
Seems there is an error in PICC_Select() function, <b>result</b> is used instead of <b>valueOfCollReg</b>:
<code>collisionPos = result & 0x1F;</code>

Code fragment:
<code>
		result = PCD_TransceiveData(buffer, bufferUsed, responseBuffer, &responseLength, &txLastBits, rxAlign);
			if (result == STATUS_COLLISION) { // More than one PICC in the field => collision.
				byte valueOfCollReg = PCD_ReadRegister(CollReg); // CollReg[7..0] bits are: ValuesAfterColl reserved CollPosNotValid CollPos[4:0]
				if (valueOfCollReg & 0x20) { // CollPosNotValid
					return STATUS_COLLISION; // Without a valid collision position we cannot continue
				}
				byte collisionPos = result & 0x1F; // Values 0-31, 0 means bit 32.
</code>

**Comment by Rotzbua** [comment]
I agree. `result` is a status code. It has nothing to do with collisionpos.
Do you tested a fixed version?
