### ISSUE TITLE
change pin layout

### ISSUE THREAD

**Issue by Skudderon** [miguelbalboa/rfid#195]
Hallo,
for the library its possible to define RST and SS pin like this:

#include <MFRC522.h>
#define RST_PIN         9           
#define SS_PIN          10         
MFRC522 mfrc522(SS_PIN, RST_PIN);

Is it also possible to define MOSI, MISO and SCK?

thanks

**Comment by Rotzbua** [comment]
No, it is hardware defined.

**Comment by mdxs** [comment]
Can be closed.
