### ISSUE TITLE
Check This NDEF addon for yout library

### ISSUE THREAD

**Issue by Gargantuanman** [miguelbalboa/rfid#198]
https://github.com/Gargantuanman/MFR522_NDEF.git

Miguel check this code I adapted from Nurun to use encode NDEF messages with the MFR522.I think will be wonderfull if you can include it in your library.

**Comment by Rotzbua** [comment]
Would not be merged. Additionally maintaining the NDEF format would be too much work. Also the actual licenses would not allow a merge.

Two separate repositories are better for the development and maintain.

I added a hint in the wiki.

So I close this issue.
