### ISSUE TITLE
some example doesn't work with MFRC522 firmware v2.0

### ISSUE THREAD

**Issue by yaroslavVl** [miguelbalboa/rfid#199]
MFRC522 Firmware Version: 0x92 = v2.0
rfid-master v1.1.8
cards (i've tried 3 cards): PICC type: MIFARE 1KB Card SAK: 08 (or 88)

examples: RFID-Cloner, rfid_default_keys.

problem: it works only if the first key is right.
But if I chage first key to wrong and change second (or other else) to right, the program try it, but it doesn't work (it is look like incorrect key).

How can I reconnect to card without take out it(card)?
	
![2016-03-22 14-25-26](https://cloud.githubusercontent.com/assets/8062959/13950173/89ad2e10-f03a-11e5-8db5-524a10fb35c3.JPG)

**Comment by mdxs** [comment]
Don't understand exactly... but is this perhaps an A and B key issue?  @yaroslavVl: please read the example code before trying it out; especially if it shows BEWARE or WARNING messages; as it might change how sections can be read after the change.

**Comment by Rotzbua** [comment]
@yaroslavVl Hi. Did you found a solution? Or a more detailed bug description?
Otherwise I will close this issue.

**Comment by Rotzbua** [comment]
no response -> close
