### ISSUE TITLE
DIRECTORY ASCII CHAR WARNING

### ISSUE THREAD

**Issue by wwin3286tw** [miguelbalboa/rfid#205]
I using Arduino ide 1.0.5r2, when open the RFID-Cloner.ino File, IDE say: must ASCII ONLY...

![forstupidapp 2016-04-18 004](https://cloud.githubusercontent.com/assets/7022841/14607561/91f2bcea-05b4-11e6-801f-797dde9c275b.png)
Could u change the file name?

**Comment by Rotzbua** [comment]
IDE 1.0 is not supported. Try latest version (>=1.6).

**Comment by wwin3286tw** [comment]
Fine, I already download new version IDE, it work.
Thanks you.
