### ISSUE TITLE
How to use with other SPI devices

### ISSUE THREAD

**Issue by Mathspy** [miguelbalboa/rfid#206]
Tiny introduction: I am new to microprocessors but not coding

Currently working on a project where I need to use an RFID reader with an SD Card and both requires the SPI library and the pins 11-13 so I researched and found out about the usage setting of SS pin LOW/HIGH to select the device that the arduino is currently communicating with

This is rather easy and I made a little switcher function to do it for me

> void switcher() {
>   if (digitalRead(CS_PIN) == HIGH && digitalRead(SS_PIN) == LOW) {
>     digitalWrite(CS_PIN, LOW);
>     digitalWrite(SS_PIN, HIGH);
>     Serial.println(F("Switched to SD"));
>   }
>   else if (digitalRead(CS_PIN) == LOW && digitalRead(SS_PIN) == HIGH) {
>     digitalWrite(CS_PIN, HIGH);
>     digitalWrite(SS_PIN, LOW);
>     Serial.println(F("Switched to RFID"));
>   }
> }

I start initially with SD on LOW (selected) and RFID on HIGH (unselected) and indeed the RFID reader is unable to read cards in that state
Then I call the switcher function and it can read, but after that I try to use the function again and nothing happens. Did my fair bit of tracking to discover that the library actually switches the RFID pin to HIGH after each check

PICC_IsNewCardPresent > PICC_Select > PCD_ClearRegisterBitMask > PCD_ReadRegister 

This line here
`digitalWrite(_chipSelectPin, HIGH);`
Line 78

So every time the library checks whether there is a card or not, it will switch my pin to HIGH which should make the Arduino select neither devices, right? But somehow it works so long as the SD is also high which is kind of weird

So rough fix would be to just turn SD between HIGH and LOW

Now my question is: What am I missing? Can I make it change that behaviour and leave my pin at LOW? Or is my rough fix not actually rough and it's the way it should be done
I am really confused

Thanks in advance though

**Comment by lmmeng** [comment]
Hello @Mathspy,
It looks like you need to refresh your knowledge about the SPI protocol.
In SPI, the communication "happens" only when the CS (chip select) signal is pulled low (by the master), acting as an "addressing" signal. In this way, you can have many chips sharing the MISO/MOSI/CLK signals.
In idle state (no communication at all), all the CS signals should be pulled high. When the master wants to speak with a slave, it (the master) selects the slave by pulling the corresponding CS signal low, sends/receives the data and pulls the CS high. 
Exactly this is happening in the MFRC522 library - when the communication ends, the CS returns to high. And exactly in the same way should happen in the case of SD communication also - the SD's CS (SS) signal should return to high after communication finishes.

Regards,
Liviu
