### ISSUE TITLE
RFID compile error with Arudino MEGA for read/write & dumpinfo

### ISSUE THREAD

**Issue by kendrickchin** [miguelbalboa/rfid#207]
#Hi, i used the code provided below and i couldn't compile ReadAndWrite due to an error,
 "invalid conversion from 'byte {aka unsigned char}' to 'MFRC522::PICC_Type' [-fpermissive]". 

![readandwrite error](https://cloud.githubusercontent.com/assets/18614996/14741721/de464922-08ca-11e6-838c-5af14b709631.png)

As for Dumpinfo, the error is "'class MFRC522' has no member named 'PCD_DumpVersionToSerial'"

![dumpinfo error](https://cloud.githubusercontent.com/assets/18614996/14741681/9a44e7ba-08ca-11e6-842e-52f66ebb80e1.png)

**Comment by Rotzbua** [comment]
Update your mfrc522 lib. I added it with commit f7f2d5d02dd545c4b27c855219437d2712d61434 .

**Comment by kendrickchin** [comment]
how do i update?

**Comment by Rotzbua** [comment]
https://www.arduino.cc/en/Guide/Libraries#toc3
or replace the files

**Comment by kendrickchin** [comment]
I cant find the download button for https://github.com/miguelbalboa/rfid/blob/master/MFRC522.cpp
