### ISSUE TITLE
Tag reading but not writing

### ISSUE THREAD

**Issue by simbadMarino** [miguelbalboa/rfid#210]
Hello friends, Im sorry for posting this here, Im not sure if this is the right place to publish it but I really need help 
I'm developing a tag reader/writer for mifare 1KB(Once it is finished I'll upload as an example for this library) but currently I realized some of the new RFid tags I bought can be read but not write. Im attaching here the dump I got from both:

THIS IS READ-ONLY:

Card UID: 13 24 36 00
PICC type: MIFARE 1KB
Sector Block   0  1  2  3   4  5  6  7   8  9 10 11  12 13 14 15  AccessBits
  15     63   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         62   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         61   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         60   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  14     59   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         58   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         57   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         56   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  13     55   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         54   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         53   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         52   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  12     51   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         50   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         49   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         48   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  11     47   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         46   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         45   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         44   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  10     43   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         42   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         41   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         40   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   9     39   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         38   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         37   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         36   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   8     35   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         34   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         33   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         32   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   7     31   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         30   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         29   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         28   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   6     27   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         26   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         25   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         24   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   5     23   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         22   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         21   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         20   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   4     19   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         18   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         17   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         16   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   3     15   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         14   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         13   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         12   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   2     11   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         10   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          9   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          8   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   1      7   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
          6   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          5   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          4   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
   0      3   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
          2   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          1   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          0   13 24 36 00  01 88 04 00  85 00 B4 2E  F0 BB 6A A8  [ 0 0 0 ] 

THIS IS READ/WRITE ABLE:

Card UID: C4 99 B0 5A
PICC type: MIFARE 1KB
Sector Block   0  1  2  3   4  5  6  7   8  9 10 11  12 13 14 15  AccessBits
  15     63   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         62   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         61   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         60   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
  14     59   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         58   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         57   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         56   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
  13     55   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         54   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         53   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         52   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
  12     51   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         50   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         49   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         48   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
  11     47   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         46   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         45   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         44   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
  10     43   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         42   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         41   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         40   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   9     39   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         38   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         37   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         36   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   8     35   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         34   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         33   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         32   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   7     31   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         30   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         29   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         28   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   6     27   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         26   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         25   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         24   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   5     23   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         22   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         21   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         20   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   4     19   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         18   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         17   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         16   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   3     15   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         14   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         13   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
         12   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   2     11   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
         10   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
          9   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
          8   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   1      7   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
          6   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
          5   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
          4   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
   0      3   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
          2   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
          1   20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  [ 0 0 0 ] 
          0   C4 99 B0 5A  B7 08 04 00  62 63 64 65  66 67 68 69  [ 0 0 0 ] 

In the second one as you see I cleared all data bytes to "20" with a function to demostrate I'm able to write every single data byte, but in the first one I cannot write. The following results came using "ReadAndWrite" example:
Card UID: 13 24 36 00
PICC type: MIFARE 1KB
Authenticating using key A...
Current data in sector:
   1      7   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
          6   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          5   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          4   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 

Reading data from block 4 ...
Data in block 4:
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Authenticating again using key B...
Writing data into block 4 ...
 01 02 03 04 05 06 07 08 08 09 FF 0B 0C 0D 0E 0F
MIFARE_Write() failed: A MIFARE PICC responded with NAK.

Reading data from block 4 ...
MIFARE_Read() failed: Timeout in communication.
Data in block 4:
 30 04 26 EE 00 00 00 00 00 00 00 00 00 00 00 00
Checking result...
Number of bytes that match = 0
Failure, no match :-(
  perhaps the write didn't work properly...

DO you think this could be related to defective Tags or perhaps there's a solution for this...

Thank you very much in advance!!

**Comment by manutdhimanshu** [comment]
I had this problem

Comment or remove the part which authenticates 'KEY B' and then try
It worked for me after that.

Hope it helped

**Comment by simbadMarino** [comment]
That solved the problem!! Thank you!! You saved me a lot of effort ;)

**Comment by mdxs** [comment]
Issue can be closed.
