### ISSUE TITLE
Bugs in examples

### ISSUE THREAD

**Issue by galcik** [miguelbalboa/rfid#211]
examples/MifareClassicValueBlock/MifareClassicValueBlock.ino, lines 168-170: && should be replaced with || Indeed, rewrite of sector trailer is required if any of the access bits is changed.

examples/ReadNUID/ReadNUID.ino, line 42: nuidPICC[3] should be replaced with nuidPICC[4] as the size of NUID is 4 bytes.

**Comment by Rotzbua** [comment]
Feel free to make a pull request.

**Comment by omersiar** [comment]
Using OR operator "double dash" makes more sense. nuidPICC byte array should be 4 byte, made changes to code.

Thank you @galcik
