### ISSUE TITLE
ESP8266 bug cpu type  

### ISSUE THREAD

**Issue by asetyde** [miguelbalboa/rfid#212]
![schermata 2016-05-22 alle 14 51 10](https://cloud.githubusercontent.com/assets/6162152/15454044/e0729e3e-202c-11e6-9437-ced6f8a0d83b.png)

Correct this with ststm32 ?? with right stm32f1 in library.json

**Comment by Rotzbua** [comment]
`ststm32` has nothing to do with the `esp8266`.

I added the notice that the library works with esp8266, but it do not mean that this library will grant continuously support. It is more like a bonus.

For `ststm32` or `stm32f1` I can not make a conclusion.

**Comment by asetyde** [comment]
oh , i did a mistake , sorry.
Can you add compability tags to permit working ?
arduino ide go but visal studio not if platform is not indicted , (it’s a good idea )
