### ISSUE TITLE
MFRC522.h Library issue

### ISSUE THREAD

**Issue by arthurjakab** [miguelbalboa/rfid#225]
Hi,

I am trying to compile the example projects and non of them are working.

I get these errors:
In file included from firmware_check.ino:28:
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:276: error: use of enum 'PICC_Type' without previous declaration
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:276: error: expected primary-expression before '{' token
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:276: error: expected ';' before '{' token
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:291: error: use of enum 'StatusCode' without previous declaration
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:291: error: expected primary-expression before '{' token
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:291: error: expected ';' before '{' token
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:337: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:354: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:355: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:356: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:357: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:358: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:359: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:360: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:365: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:367: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:368: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:369: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:370: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:371: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:372: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:373: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:374: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:375: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:376: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:381: error: 'StatusCode' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:384: error: expected ';' before '(' token
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:385: error: 'PICC_Type' does not name a type
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:388: error: expected ';' before '(' token
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:394: error: 'PICC_Type' has not been declared
C:\Program Files\Arduino\libraries\rfid/MFRC522.h:413: error: 'StatusCode' does not name a type

I have copied the mfrc522.h and .cpp files in the libraries folder.

Please, can anyone take a look at this?

**Comment by Rotzbua** [comment]
see https://github.com/Rotzbua/rfid/blob/e90031305f02d457ff94bda519349ebcc519e855/README.rst#compatible-ide
