### ISSUE TITLE
Working with Arduino 101

### ISSUE THREAD

**Issue by prazek** [miguelbalboa/rfid#226]
Does anyone know if this is compatible with Arduino 101? Sketch was written sucessfully, but it doesn't seem to work.

**Comment by Rotzbua** [comment]
Read old issues #225

**Comment by prazek** [comment]
Thanks for the comment that doesn't add anything new to the disscussion. I have read the documentation and I know what boards are officially supported. If Arduino 101 is not one of them then I would like to know why and what should I fix to make it work so everyone could use it.

**Comment by Rotzbua** [comment]
Sorry, I read too fast. Arduino 101 != Arduino IDE 1.01, sorry for my mistake.
I think it should work. Maybe replace unfixed integers with fixed integers.

**Comment by prazek** [comment]
I will firstly check if I solted RC522 properly using older version of arduino. If I will make it work I will send patch adding support for 101 or fix the issue. Thanks!

**Comment by Rotzbua** [comment]
@prazek any progress? does it work with board `Arduino 101`?

**Comment by prazek** [comment]
I managed to make it work on older arduino by replacing the RFC522. Haven't tried with 101, but I will check if it works. If so I will update documentation.

**Comment by prazek** [comment]
Ok, I finally got tome ti test it.
https://github.com/miguelbalboa/rfid/pull/246
everything works.
