### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by KC38** [miguelbalboa/rfid#229]
I used Arduino Uno and RFID reader RC522 with connection checked more than thrice, still the reading and writing procedure does not work. Please help ASAP.

**Comment by KC38** [comment]
Does the port affect it? I've connected it to COM5

**Comment by Rotzbua** [comment]
@KC38 [How to ask questions the smart way](http://www.catb.org/esr/faqs/smart-questions.html#intro) and it is not a intended use case of the library nor a software issue

**Comment by LoyalNine1487** [comment]
Did you read the first line of the "Read Me?"

**Comment by Rotzbua** [comment]
@LoyalNine1487 Sure.. I misunderstood this confusing issue report wrong..
Anyway I hate the term `ASAP` and hobby..
