### ISSUE TITLE
Does not detect the card

### ISSUE THREAD

**Issue by sriranjanr** [miguelbalboa/rfid#231]
![output rfid 1](https://cloud.githubusercontent.com/assets/8640547/17831265/befe162c-6701-11e6-944a-2ac3cb798c87.jpg)
I am using your library with the RC522. I am not able to detect the card.I am using arduino 1.6.5 on windows and the mega 2560. I am attaching the serial monitor output screen.Please let me know how to get it working.I double checked all the connection and mentioned the right pin in the code but still it does not work.The power supply to the RC522 is from arduino 3.3v and the LED on it glows bright.

**Comment by Rotzbua** [comment]
@sriranjanr Try different tag. Most times the hardware is defect. Contact your supplier.
