### ISSUE TITLE
Philips Mifare 1 S50 tag compatible?

### ISSUE THREAD

**Issue by stevekramer99** [miguelbalboa/rfid#233]
Hello I got this reader kit on Ebay:

http://www.ebay.com/itm/371104303227

The reader has no response to the keychain tag but responds to the card.  The description says the tag has the following IC:  "Philips Mifare 1 S50"  Should the library work with this tag?

Thanks,
Stephen

**Comment by simbadMarino** [comment]
It should work, recheck wiring and try not to use a protoboard,  always use a direct wire soldering. 
Good.luck!

Enviado desde BlueMail

**Comment by stevekramer99** [comment]
The reader works fine with the card, but does not respond at all to the
keychain tag.  I don't touch the wiring between reading them just scan each
one sequentially.  There is no response to the keychain fob.  It must be
faulty, please send a replacement correctly working tag.

**Comment by stevekramer99** [comment]
I AM SORRY, I SENT THIS TO THE WRONG PERSON!  I was supposed to send this
to the ebay seller!

Thanks for your help.

**Comment by Rotzbua** [comment]
@stevekramer99 Did it work with the Philips Mifare 1 S50 ?
