### ISSUE TITLE
SPI speed change 

### ISSUE THREAD

**Issue by dagnall53** [miguelbalboa/rfid#242]
SPI_CLOCK_DIV_4 is used to set speed in many places.
eg:SPI.beginTransaction(SPISettings(SPI_CLOCK_DIV4, MSBFIRST, SPI_MODE0));
But this is defined in SPI code for an Arduino. 
Please make the Spi speed setting a MRFC define so that the clock speed and be altered.

**Comment by tuyethoa08041997** [comment]
Just wait, my commit is imcoming :v:

**Comment by Rotzbua** [comment]
see #241

**Comment by Rotzbua** [comment]
will be changed by #276
