### ISSUE TITLE
Question about reader compability

### ISSUE THREAD

**Issue by TomHyhlik** [miguelbalboa/rfid#248]
The reader MFRC522 doesn't react to any card instead of the one which was in the package with the reader. It doesn't even react to student card ISIC. Why is that so?
Thanks for any explanation.

**Comment by Rotzbua** [comment]
Not compatible card type.

**Comment by Rotzbua** [comment]
@TomHyhlik Did you solved your problem? Can you share your experience with us? Otherwise I will close this issue within 14 days. Thanks.
