### ISSUE TITLE
Clone reader error

### ISSUE THREAD

**Issue by tib1989** [miguelbalboa/rfid#251]
Hi, 

My goal is to copy my first card to my second card wich is brand new. I get some errors:

When I read my first card i get that:

![image](https://cloud.githubusercontent.com/assets/22504923/18926112/716ee9ce-85ae-11e6-90fe-a0ba277c5b78.png)

on my second card i get that 

![image](https://cloud.githubusercontent.com/assets/22504923/18926139/99506cd8-85ae-11e6-98a6-579611142526.png)

but when i try to copy the data from my first card i get that

![image](https://cloud.githubusercontent.com/assets/22504923/18926168/b3c396a8-85ae-11e6-9d50-f803ab407106.png)

Anyone got an idea ?

Thank you

**Comment by thomaslc66** [comment]
Hi, same problem here.

For the first timeout in communication you need to keep the RFID card to the reader without moving. 

But for the copy of the card, i have the same problem. I've made some research and they told it can be a problem with the used key ( A or B), but the library is testing both, so I don't know and i'm also searching for a solution

**Comment by simbadMarino** [comment]
Hello folks, I had a similar issue with another program, try using authentication only with one key A or B not both. That resolved my problems, I didn't analyzed deep enough to give u a reason why this is happening but it helped me. Good luck! 

⁣

Enviado desde BlueMail

​

**Comment by Rotzbua** [comment]
@tib1989 Did you solved your problem? Can you share your experience with us? Otherwise I will close this issue within 14 days. Thanks.
