### ISSUE TITLE
UART support?

### ISSUE THREAD

**Issue by mortenmoulder** [miguelbalboa/rfid#257]
Hello. Awesome project! So I got an Elechouse RFID reader/writer v1.1. The thing hooks up using UART (RXD and TXD), but as far as I can see, this project uses SPI.

Would I be able to hook up this UART board and use it with this project, or do I have to find one that supports SPI?

Thanks!

**Comment by Rotzbua** [comment]
I think you only have to modify/extend the communication functions. Just look at the data sheet. Best.

**Comment by Rotzbua** [comment]
@mortenmoulder Will you implement it or can I close this issue?

**Comment by mortenmoulder** [comment]
@Rotzbua I guess you can close it. I don't have the capability of changing out any of this I'm afraid.

**Comment by Rotzbua** [comment]
Okay.
