### ISSUE TITLE
PN532 Code?

### ISSUE THREAD

**Issue by JohnMaree** [miguelbalboa/rfid#260]
Hi, 

Am wondering if and how this can be adapted for the PN532 module. I cannot seem to find code for this anywhere and I am not advanced enough at coding to write my own code for this from scratch. 
Any help is appreciated. 

Thank you,

**Comment by Rotzbua** [comment]
Why should this library be adapted for the PN532?? There are a lot of libraries for the PN532.

**Comment by JohnMaree** [comment]
There are libraries or code that I can't find anywhere for the PN532 😕 like the change UID or recover a fried card 😕 
But thanks for the help

**Comment by Rotzbua** [comment]
Then you have to open an issue on their libraries. It is more difficult to adopt this library than extend an existing library.
