### ISSUE TITLE
Can't read RFID after write by NFC Smartphone

### ISSUE THREAD

**Issue by DreCrypt** [miguelbalboa/rfid#262]
I've use DumpInfo.ino to my new RFID, and I can read the block of RFID..

Next..
I write the RFID with NFC on my Smartphone..
But, PCD_Authenticate() failed: Timeout in communication always appear.

Please help me...

**Comment by Rotzbua** [comment]
@DreCrypt This is not a serious issue report. No details about token nor compiler/software version ... Correct your issue or I close it.
