### ISSUE TITLE
How to detect communication between Arduino and Card reader

### ISSUE THREAD

**Issue by Mario-H** [miguelbalboa/rfid#27]
Hi Miguel,

First: Thanks for the library!

Not an issue but just a tip I wanted to share.

Received my reader yesterday and hooked it up to my adruino and loaded your DumpInfo sample.
I tried the card and keyfob that came with the reader and nothing happened. Checked connections etc. but no luck.
To figure out if the problem was in the connection I added a command to read the version of the MFRC522 chip from Page3 Test register "VersionReg".
This gave me a positive result so now I knew the comminication between Arduino and the reader was functioning.
Finaly got hold of some other cards today, tested them and they did work.

So for anyone having doubt about the Arduino to reader connection add these lines to the DumpInfo sample just below the line  
mfrc522.PCD_Init(); // Init MFRC522 card

Serial.print("MFRC522 software version = ");
Serial.println(mfrc522.PCD_ReadRegister(mfrc522.VersionReg),HEX);

According to the 2014 edition of the MFRC522  datasheet (page 65 table 132) it should return:
0x91 for version 1
0x92 for version 2

When communication fails you get 0 returned form the lib.

Cheers,

Mario

**Comment by Boby71** [comment]
@Mario-H , thank you so much - this topic is five years old and still it saved my ass for not reliably working RFID-solution out in the field. I've just put the read into a bool function and in the sketch I just check if (! reader_reachable) {...init...}

Thanks a lot!
