### ISSUE TITLE
RFID Arduino activated content

### ISSUE THREAD

**Issue by abryan156** [miguelbalboa/rfid#287]
Greetings,
I'm very new to Arduino and am trying to get my RFID Arduino set up to open content. Either a webpage or a file on my computer. Any ideas are greatly appreciated.
Thanks

**Comment by bghost4** [comment]
You will have to write a program that sits on the computer, and is
monitoring the serial Port, then when you scan an rfid card it will send
data over to the computer program that will decide what the computer will
do.

**Comment by abryan156** [comment]
Thank-You, that is very helpful. Do you have any tutorial suggestions that might help me write this kind of program? I'm really new to all of this, any help you could offer would be really appreciated.

**Comment by bghost4** [comment]
Hmm I can't think off any direct tutorials, but in java you could use
awt.desktop class to open a file or webpage. There is also a serial Port
library... Jserialport or something like that. It would allow you to
connect to the arson serial Port and look at incoming data.

**Comment by bghost4** [comment]
The serial Port library is jssc.

**Comment by abryan156** [comment]
Thanks so much for your help, this is a huge lead.

**Comment by Rotzbua** [comment]
@abryan156 Can it be closed?

**Comment by abryan156** [comment]
Sure!
