### ISSUE TITLE
Relationship: between rfid here and MFR522 'GitHub Community'...

### ISSUE THREAD

**Issue by DrLou** [miguelbalboa/rfid#289]
Not exactly an issue - more of a clarification request?

How are rfid here and MFRC522 'GitHub Community' - currently at v1.1.8, as included with the Arduino IDE Libs, related?

I imagine a git pull here gets latest incorporations... Should rfid supercede MFRC522; IE, should we simply uninstall the IDE-provided libs?

**Comment by DrLou** [comment]
Thanks! and it's great stuff!

**Comment by jamieduk** [comment]
How do i use? Read a ky then pass a blank for it to write?
