### ISSUE TITLE
library for esp8266 nonos sdk

### ISSUE THREAD

**Issue by mmmmar** [miguelbalboa/rfid#294]
I port it to esp8266 partly.
https://github.com/mmmmar/esp8266-mfrc522

could I realase it in my repository?

**Comment by Rotzbua** [comment]
Yes, why not? :)

Some points:
- It would be nice, if you can add an additional notice in your file https://github.com/mmmmar/esp8266-mfrc522/blob/master/mfrc522/mfrc522.c to this library.
- And maybe you publish your port under a licence, so other people can use your library.
- You can add your port under https://github.com/miguelbalboa/rfid#compatible-boards if you make an pull request.

Best

**Comment by mmmmar** [comment]
I'm improving it @Rotzbua

**Comment by Rotzbua** [comment]
Thanks for your work. I added you as reference into the readme 9e48c308da4660c29ec84eacfad5e4146c8b3a02 .
