### ISSUE TITLE
No rfid tag/card working and serial monitor showing Ver: 0x0

### ISSUE THREAD

**Issue by muditbatra** [miguelbalboa/rfid#296]
* OS version: Windows 8
 * Arduino IDE version: 1.0.6
 * Arduino device: MEGA

No RFID tags/cards  (mifare cards) were detected. No interrupts were there. The serial monitor only showed, "Ver: 0x0"

Things I have tried so far:

- I have double checked the connections and all are done according to the typical connections of MEGA.

- I have tried and replaced arduino MEGA and the RFID RC-522 but I have got no success.

Would be great if you could help.
Thank you

**Comment by Rotzbua** [comment]
Affected file(s) or example(s)? firmware check?

**Comment by Rotzbua** [comment]
Seems duplicate to #299 . Closed in favor of the newer one.
