### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by nydss** [miguelbalboa/rfid#297]
### Step 1: Are you in the right place?
GitHub issues only for **bugs** or **improvements** of the library. All other topics, e.g. hardware/programming, will be closed.

For general support from the community, see [Arduino Forum](https://forum.arduino.cc/) or [StackOverflow](https://stackoverflow.com/questions/tagged/mifare).

### Step 2: Describe your environment

 * OS version: windows 10
 * Arduino IDE version: 1.8.1
 * MFRC522 Library version: 
 * Arduino device: uno
 * MFRC522 device: rc522
  
### Step 3: Describe the problem

need to compare the read rfid tag with a uid already declared in the program
  
#### Steps to reproduce:

   email @ nidhicjoshi95@gmail.com

**Comment by Rotzbua** [comment]
>GitHub issues only for bugs or improvements of the library.  All other topics, e.g. hardware/programming, will be closed.
