### ISSUE TITLE
[Lib] Changes to next version

### ISSUE THREAD

**Issue by Rotzbua** [miguelbalboa/rfid#311]
### Planned for 1.4.x

Remove:
* [x] ```#define MFRC522_SPICLOCK SPI_CLOCK_DIV4 // MFRC522 accept upto 10MHz```
* [x] script `Makefile` is it required/usecase? (remove/update) @mdxs 

Optimize:
* [x] replace `NULL` with `nullptr`

### Planned for Fork (and will not(!!111) be implemented in this repository)

Add:
* [x] injectable ```SPISettings(MFRC522_SPICLOCK, MSBFIRST, SPI_MODE0)```

Remove:
* [x] ```MFRC522(byte resetPowerDownPin);``` (breaking)
* [x] ```void PCD_Init(byte resetPowerDownPin);``` (breaking)
* [x] ```#define ```
* [x ] **droped in favor of CI** `library.json`, because platformio now supports `library.properties` so remove duplicate

Optimize:
* [ ] rename `MIFARE_SetAccessBits` to `MIFARE_CalculateAccessBits`, because it do not set any bits on picc

CI/CD system: (This require some main(!) repository changes)
* [ ] version release/process
* [ ] keywords generator
* [ ] changelog generator
* [ ] spell checker

Documentation:
* [ ] git pages with class documentation

Move:
* [x] extra class for "hardware modification" fcts: (breaking)
```c++
	bool MIFARE_OpenUidBackdoor(bool logErrors);
	bool MIFARE_SetUid(byte *newUid, byte uidSize, bool logErrors);
	bool MIFARE_UnbrickUidSector(bool logErrors);
```
* [x] extra class for debugging stuff: (proxy used) 
```c++
	static const __FlashStringHelper *GetStatusCodeName(StatusCode code);
	static const __FlashStringHelper *PICC_GetTypeName(PICC_Type type);
```
* [ ] extra class for debugging stuff:
```c++
	void PCD_DumpVersionToSerial();
	void PICC_DumpToSerial(Uid *uid);
	void PICC_DumpDetailsToSerial(Uid *uid);
	void PICC_DumpMifareClassicToSerial(Uid *uid, PICC_Type piccType, MIFARE_Key *key);
	void PICC_DumpMifareClassicSectorToSerial(Uid *uid, MIFARE_Key *key, byte sector);
	void PICC_DumpMifareUltralightToSerial();
```
(breaking, maybe aliasing)

To check:

Feel free to discuss :)

**Comment by omersiar** [comment]
Can we configure Interrupt registers, so anyone can benefit from simple attachInterrupt function.

I should try to code it, it will be good learning.

**Comment by Rotzbua** [comment]
@omersiar good idea, something like?:
```c++
void PCD_ActivateInterrupt(byte BitmaskInterruptTriggers);
void PCD_ClearInterruptBit();
```
But I think you have to invest some time to find out how exactly the interrupt mechanism works. The example https://github.com/miguelbalboa/rfid/blob/master/examples/MinimalInterrupt/MinimalInterrupt.ino is good but the fct `activateRec` seems for me like a workaround(?) .

A simple function to attach a pin like `PCD_AttachInterruptPin(byte)` seems difficult because it is not very good to let it work under other architectures, so I would disadvice this solution.

**Comment by lmmeng** [comment]
Hi @Rotzbua,
the activateRec() function is the "lighter" way I found to energize the board (antenna). Without it the detection of a new card will not work. It is the meaning of the comment in the loop():
```
  // The receiving block needs regular retriggering (tell the tag it should transmit??)
  // (mfrc522.PCD_WriteRegister(mfrc522.FIFODataReg,mfrc522.PICC_CMD_REQA);)
  activateRec(mfrc522);
```
"Lighter" (and fast) because I haven't implemented any check if the commands are passing through, but was just a quick try to see if it has a chance to work. 
Probably there are better (but more time consuming) way to do it, as said, was just a quick hack.

Best regards,
Liviu

**Comment by ivankravets** [comment]
I recommend keeping `library.json`, it is more flexible than `arduino.properties`: support platforms, keywords, and other useful things for @PlatformIO registry.

In any case, if you would like to switch on `arduino.properties`, I can make some changes in the Registry.
