### ISSUE TITLE
How to reverse order the UID returned from MiFare

### ISSUE THREAD

**Issue by akeilox** [miguelbalboa/rfid#316]
A quick question;

How can I output a reverse ordered UID with, for instance, the ReadUIDMultiReader example;

UID: 90 D7 52 C5  (this is what current code returns for mifare 1k card)

I need this in reverse order like:
UID: C5 52 D7 90

So when I convert it to decimal it shows a 'matching' number; because thats how an existing RFID reader shows (reversed hex UID, converted to decimal) and would like to match/check the numbers with arduino.

I have tried google but there is no clear explanation for new joiners on how to go about this.

Will appreciate if you can shed some light.

**Comment by Rotzbua** [comment]
Not a library issue. This is about programming. Use Arduino forum or stackoverflow.
