### ISSUE TITLE
Multi RFID

### ISSUE THREAD

**Issue by Khamphai** [miguelbalboa/rfid#320]
i have a problem when i use two RFID and use Example code of MFRC522 ReadUidMultiReader.ino file and follow the pin of circuit in doc on that file (Arduino UNO) ,the result a first RFID do not read key but second can read key and if i pull out second RFID the result is first RFID can read the key... please help me about the this problem thank you

**Comment by lmmeng** [comment]
Maybe you can find an answer in #284?
