### ISSUE TITLE
Invalid library found in C:\Users\Lepy\Desktop\Arduino\libraries\RC522_RFID_NFC_Utilities-master: C:\Users\Lepy\Desktop\Arduino\libraries\RC522_RFID_NFC_Utilities-master

### ISSUE THREAD

**Issue by Radulepy** [miguelbalboa/rfid#325]
Arduino: 1.8.2 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\Lepy\Desktop\Arduino\libraries\Robot_Motor\RC522_RFID_NFC_Utilities-master\RFIDScanningExample\RFIDScanningExample.ino:22:34: fatal error: RC522_RFID_Utilities.h: No such file or directory

 #include <RC522_RFID_Utilities.h>

                                  ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.
Invalid library found in C:\Users\Lepy\Desktop\Arduino\libraries\RC522_RFID_NFC_Utilities-master: C:\Users\Lepy\Desktop\Arduino\libraries\RC522_RFID_NFC_Utilities-master
Invalid library found in C:\Users\Lepy\Desktop\Arduino\libraries\RC522_RFID_NFC_Utilities-master: C:\Users\Lepy\Desktop\Arduino\libraries\RC522_RFID_NFC_Utilities-master

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

i got this when i try to open the example.
Anybody help? Thank you

**Comment by Rotzbua** [comment]
This is not the library which are you search. Off topic:  i think you have a whitespace in your path.
