### ISSUE TITLE
Sombody knows why this happens with my RFID card?

### ISSUE THREAD

**Issue by Perhapsody** [miguelbalboa/rfid#329]
I was just playing arround with the RC522 trying to copy a Bus Card that we use here in Argentina.
When i run the InfoDump this pops up no matter the distance i place the card.  **sib**
![2017-07-25_01-17-23](https://user-images.githubusercontent.com/28969925/28555552-0e1d6cb4-70d7-11e7-8f30-89a460bb0a99.png)

Does this mean that the blocks are empty? or just i cant read them for a reason i cant understand?

Sorry for my noobness and the bother, im just playing around xD. 
(Initially my idea was to clone the Bus card, thus having a backup of it. But i think i need a UID Changeable card to make this possible)

**Comment by Rotzbua** [comment]
The sectors are protected with a key. You can not copy them unless you have this keys. There is no way to get this keys with this library.

**Comment by Carlokko** [comment]
I was doing just the same thing with my Italian Bus Card and got the same error.  @Rotzbua, @Perhapsody, any ideas on what library I could use to get the keys?

**Comment by Rotzbua** [comment]
Restoring the keys to get access to protected data would be illegal. Issue locked.
