### ISSUE TITLE
c++11 compiler error

### ISSUE THREAD

**Issue by rogerrnichols** [miguelbalboa/rfid#335]
I am using trying to compile the DumpInfo example for an Arduino Uno.
Windows 10
RFID version 1.3.6
Arduino 1.8.3
Uno
MFRC 522 (generic,, but not attached for sketch compile test)

I tried copying the unzipped master to the libraries and then including a zipped file.
Both attempts to Verify/compile failed with the c++11 error message.

**Comment by rogerrnichols** [comment]
I am using trying to compile the DumpInfo example for an Arduino Uno.

**Comment by Rotzbua** [comment]
@rogerrnichols please edit your first post and fill in the required informations. thanks.

**Comment by rogerrnichols** [comment]
Thanks for any help.

Windows 10
RFID version 1.3.6
Arduino 1.8.3
Uno
MFRC 522 (generic,, but not attached for sketch compile test)

I tried copying the unzipped master to the libraries and then including a
zipped file.
Both attempts to Verify/compile failed with the c++11 error message.

**Comment by Rotzbua** [comment]
I could not reproduce your error. Please add a screen shot of the error. Thanks.

**Comment by rogerrnichols** [comment]
Arduino: 1.8.3 (Windows 10), Board: "Arduino Uno"

WARNING: Category '' in library EEPROM is not valid. Setting to
'Uncategorized'
WARNING: Category '' in library SPI is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library SoftwareSerial is not valid. Setting to
'Uncategorized'
WARNING: Category '' in library Wire is not valid. Setting to
'Uncategorized'
Warning: platform.txt from core 'Arduino AVR Boards' contains deprecated
recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags}
{compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}",
automatically converted to
recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags}
{compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider
upgrading this core.
In file included from
C:\Users\Roger\Documents\Arduino\libraries\rfid-master\src/MFRC522.h:78:0,

                 from
C:\Users\Roger\Documents\Arduino\libraries\rfid-master\examples\DumpInfo\DumpInfo.ino:37:

C:\Users\Roger\Documents\Arduino\libraries\rfid-master\src/require_cpp11.h:9:2:
error: #error "This library needs at least a C++11 compliant compiler,
maybe compiler argument for C++11 support is missing or if you use Arduino
IDE upgrade to version >=1.6.6"

 #error "This library needs at least a C++11 compliant compiler, maybe
compiler argument for C++11 support is missing or if you use Arduino IDE
upgrade to version >=1.6.6"

  ^

exit status 1
Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Rotzbua** [comment]
Strange, maybe you have an old toolchain installed. "tools" -> "board manager" -> look for update

`rfid-master` seems you also did not used the library manager. your description says `RFID version 1.3.6` which is wrong. just use releases https://github.com/miguelbalboa/rfid/releases
