### ISSUE TITLE
Arduino Nano + RFID RC522 + Ethernet shield W5100

### ISSUE THREAD

**Issue by peter1a** [miguelbalboa/rfid#338]
I have this Arduino Nano, Ethernet shield W5100 and RC522 as card reader. They are sharing pins D13, D12, D11, D10 is SS pin for W5100 D8 is SS pin for RC522. Problem is with pin D12, like it doesn't share it.

For example if I unplug D12 from W5100, RC522 reader works, if I wire it back it doesn't work anymore. W5100 works no matter if RC522 is wired or not, so problem would be somehow with pin D12.

Does anybody have some ideas, what I'm doing wrong right here?

**Comment by Rotzbua** [comment]
Seems to be a SPI problem. See: https://github.com/arduino/Arduino/issues/6694#issuecomment-327145487
