### ISSUE TITLE
Change return value on PCD_DumpVersionToSerial if comm fails

### ISSUE THREAD

**Issue by CarloMara** [miguelbalboa/rfid#339]
Hi Folks,

While testing the library on an ESP32, I found out  _PCD_DumpVersionToSerial_ which is very nice function, because it allows us to see weather or not the comms are working correctly.

I'd like to add a different return value if the test fails, so that the program flow could be easily changed.

If it's ok for everyone I could make a pull request or send a patch file here.

Cheers,
Carlo

**Comment by Rotzbua** [comment]
Hi,
`PCD_DumpVersionToSerial` is just for debugging by serial output. So no return should be provided.
Best

**Comment by Rotzbua** [comment]
@CarloMara I thought about your suggestion. I think you want `void PCD_Init();` to return the status of the initialization process?
So a change to `bool PCD_Init();` where return of `true` indicates a successful initialization and false an error?
Otherwise you may use `bool PCD_PerformSelfTest();` to check the mfrc522.
Best regards

**Comment by CarloMara** [comment]
Yes, you stole my words. 

From what I gather by looking at some examples `PCD_PerformSelfTest();` returns the same thing if the chip doesn't respond or it's an unknown firmware.

I would have imagined that `bool PCD_Init();` could give us some finer controls, like telling me that we can communicate, even if it can't detect the version of the firmware.

Thanks,
Carlo

**Comment by Rotzbua** [comment]
I guess maybe the code from `MFRC522::PCD_DumpVersionToSerial` is enough:
```c++
byte v = PCD_ReadRegister(VersionReg);
// When 0x00 or 0xFF is returned, communication probably failed
if ((v == 0x00) || (v == 0xFF))
return false;
return true;
```

But maybe there is a better way? Would be good if you can check the mfrc522 documentation. Your pull request will be welcome.

**Comment by szotsaki** [comment]
I checked the documentation and I'm not sure I found a better way.

Those that I found:
- `Status2Reg::ModemState[2:0]`: the problem with this it can be in any state, if a PICC is nearby, not just in `idle`.
- `ErrorReg`: mostly for PICC related errors.
- Test buses would be an overkill and for those we have to access to pin `AUX1` or `AUX2`.

**Comment by Rotzbua** [comment]
Implemented this for `PCD_Init` at the fork.
