### ISSUE TITLE
how to display serial monitor in Liquid crystal 12c

### ISSUE THREAD

**Issue by henryprobosantoso** [miguelbalboa/rfid#340]
### Step 1: Describe your environment

 * OS version: win 7 ultimate
 * Arduino IDE version: 1.6.10
 * MFRC522 Library version: im forget
 * Arduino device: uno
 * MFRC522 device: 
  
### Step 2: Describe the problem
I have successfully tried the example "accesscontrol" , I want to show the sentence that is on the serial monitor on the lcd (i use liquid crystal 12c) , I have downloaded Arduino-LiquidCrystal-I2C-library-master, but I do not know which part of the accesscontrol example I should change
thank youuuu

**Comment by omersiar** [comment]
Please consider using Arduino Forum. This GitHub issue facility is not for user help.

**Comment by Rotzbua** [comment]
Correct, github issues to fix or improve library, forum for projects. So I closed it.
