### ISSUE TITLE
RC522S RFID card

### ISSUE THREAD

**Issue by ingfranco** [miguelbalboa/rfid#341]
Hi
Please, someone can tell me if we can use RC522S readers (not MFRC522) with Arduino Controller?
I need a reader with separate antenna, and on Aliexpress / Ebay this reader is the only one that have separate antenna. I try a sample sketch with arduino DUE but if I connect MFRC522 reader, all is OK, but if I change reader with RC522S,  I cannot read the same tag / fob.
Thank's for replay
Franco

Here is the reader I will use
![rc522](https://user-images.githubusercontent.com/6497666/31475670-6adfbc90-af02-11e7-9820-d538e273881d.jpg)

**Comment by Rotzbua** [comment]
Reported firmware version? Test with `firmware_check.ino`?

**Comment by ingfranco** [comment]
Hi, Rotzbau

The firmware_check.ino report is:

Found chip MFRC522 Firmware ver. 0xFF.
Digital self test by MFRC522 failed.

**Comment by Rotzbua** [comment]
Ok, then the arduino can not communicate with the module. Firmware ver. 0xFF or 0x00 means that something went wrong.

**Comment by Rotzbua** [comment]
@ingfranco Did you found a solution?
