### ISSUE TITLE
Not working on SAMD21 based boards (MKR1000, Feather M0, Zero)

### ISSUE THREAD

**Issue by PTS93** [miguelbalboa/rfid#347]
* OS version: Ubuntu 17.04
 * Arduino IDE version: 1.8.3
 * MFRC522 Library version: master
 * Arduino device: Adafruit Feather M0
 * MFRC522 device: RFID-RC522
  
I'm trying to use the library with the Feather M0 which uses the SAMD21 (ARM Cortex M0+) also present on all newer Arduinos like the MKR1000 and Zero.
Unfortunately the library fails to communicate with the RC522 (hangs for ages in init and returns firmware version 0x00 after a while). I tested the same board with an Arduino Nano which worked fine. Any ideas why it doesn't work on the Feather?
Anything SPI wise that is not using standard SPI.h function calls that causes the incompatibility?

**Comment by Rotzbua** [comment]
Can you try `1.6.3` https://github.com/miguelbalboa/rfid/releases ?

**Comment by PTS93** [comment]
I tried 1.3.6 and 1.3.5, same issue.

**Comment by PTS93** [comment]
Just to complete the documentation this is my wiring:
https://imgur.com/a/AKhrP

I checked it 5 times now, seems all in order.

I'm trying out the DumpInfo example.

**Comment by Rotzbua** [comment]
- [x] Ok, wiring looks good.
- [x] According to your report it not depends on recent changes.
- [ ] Check out changes by #344 
- [ ] Maybe the pin config cause your error noticed in https://github.com/miguelbalboa/rfid/pull/344#issuecomment-340320910

---
General note for migrating to feather m0: https://learn.adafruit.com/adafruit-feather-m0-basic-proto/adapting-sketches-to-m0

**Comment by PTS93** [comment]
Doing a hard reset as suggested in that bug report indeed did the trick for me. Maybe that is something that should be added to PCD_Init() by default? Or is there another reason why there is deliberately no hard reset? If so maybe an optional "do hard reset" argument for PCD_Init() might be the way to go?

**Comment by Rotzbua** [comment]
Should be fixed with feda7b55f984c0030ab0eac2d573161815ce3ceb .

**Comment by blooem** [comment]
I am having the same problem.

Using latest version of code
Arduno 1.8.5
Mac OSX

Just using standard ReadWrite Example works fine on a 32u4 board, however on the M0 it does not display much.
Here is wiring (Although it works on 32u4 so I know its not that): https://photos.app.goo.gl/WJMeFrJUu7ADLxKQ2
Here is a snippet from arduino serial output
<img width="672" alt="screen shot 2018-02-04 at 6 07 36 pm" src="https://user-images.githubusercontent.com/36143001/35785606-5bb5cd66-09d6-11e8-8899-384cbd169b8f.png">

Any help would be appreciated!
-Brandon

**Comment by Rotzbua** [comment]
> Using latest version of code

@blooem Version of the code: git master or 1.3.6?

**Comment by blooem** [comment]
@Rotzbua 
<img width="678" alt="screen shot 2018-02-04 at 6 43 48 pm" src="https://user-images.githubusercontent.com/36143001/35786345-7ebc9c54-09db-11e8-91d4-5f214e5e2d43.png">

**Comment by blooem** [comment]
I am willing to pay for support if anyone is interested. This is the only library that I have even remotely got to work, and really need to finish this project.

Thanks,
B

**Comment by PTS93** [comment]
You should try the latest version from git not 1.3.6. The thing described here is already fixed.
