### ISSUE TITLE
Use library at Chipkit uno 32? 

### ISSUE THREAD

**Issue by gilcanetasdias** [miguelbalboa/rfid#351]
I'm trying to use the library with the Chipkit uno 32, but i cant. When i upload to board and then go to serial monitor, nothing appears to me.

Does anyone make it work?

Thanks

**Comment by Rotzbua** [comment]
As written in the readme there was a try to make this happen: https://github.com/miguelbalboa/rfid/pull/230
Maybe ask  @majenkotech who done this pull request or better ask in a chipkit forum.
This library focus arduino, so there will be no changes to make it work with chipkit.

Best.
