### ISSUE TITLE
rfid_default_keys always skip the first key

### ISSUE THREAD

**Issue by blovercat** [miguelbalboa/rfid#357]
```c++
bool try_key(MFRC522::MIFARE_Key *key)
{
    bool result = false;
    byte buffer[18];
    byte block = 0;
    MFRC522::StatusCode status;
    
    // http://arduino.stackexchange.com/a/14316
    if ( ! mfrc522.PICC_IsNewCardPresent())
        return false;
    if ( ! mfrc522.PICC_ReadCardSerial())
        return false;
    // Serial.println(F("Authenticating using key A..."));
    status = mfrc522.PCD_Authenticate(MFRC522::PICC_CMD_MF_AUTH_KEY_A, block, key, &(mfrc522.uid));
```

IF Called:

if ( ! mfrc522.PICC_IsNewCardPresent()) return false;
 if ( ! mfrc522.PICC_ReadCardSerial()) return false; 
before every re-authenticate. 
will skip the FIRST item in array 'knownKeys'
 so,you will never test the default key FF FF FF FF FF FF

**Comment by Rotzbua** [comment]
@blovercat Please update your report. Library version is missing. Also please provide a step by step explanation or suggested vs observed. I do not understand what you mean.
