### ISSUE TITLE
Arduino Due Pin Layout and Code for SPI (MOSI, MISO, SCK, etc..)

### ISSUE THREAD

**Issue by RGVGreatCoder** [miguelbalboa/rfid#358]
I notice you don't have a pin layout nor example using an Arduino Due. Would you know if your library may work following this Pin layout?

Pins	SPI	        Due
1	SDA (SS)  10
2	SCK	        SCK1
3	MOSI	MOSI1
4	MISO	MISO1
5	IRQ	        *
6	GND	GND
7	RST	        Reset
8	+3.3V	3.3V

Also, how would your code read to refer to the SPI pins on above layout?
Thank you and hopefully you find some time to reply. I will appreciate. ... 👍

**Comment by Rotzbua** [comment]
If you can verify the pin layout you can make a pull request. For wiring and programming questions please use stackoverflow or arduino forum. Thanks.
