### ISSUE TITLE
Not working on STM32F205 M3

### ISSUE THREAD

**Issue by glowingsteam** [miguelbalboa/rfid#360]
### Step 1: Describe your environment

 * OS version: Windows 10 64-bit
 * Arduino IDE version: 1.8.5
 * MFRC522 Library version: v1.3.6 from Github releases 
 * Arduino device: Adafruit WICED Feather - https://www.adafruit.com/product/3056
 * MFRC522 device: Sunfounder RFID-RC522
  
### Step 2: Describe the problem

I am trying to load the readAndWrite example yet the error I get is as follows:
![image](https://user-images.githubusercontent.com/36467270/36189365-e4d9115c-1106-11e8-95d5-8eb96560d7c4.png)

I presume there is probably nothing to be done about this, and I searched around the web with no luck. If there's any fix please let me know. : )

I have also put a ticket on the adafruit forums, so for anyone else looking for a fix in the future and happens to stumble on this hopefully there is an answer here or at https://forums.adafruit.com/viewtopic.php?f=57&t=131057 for you.

Thanks,
-B

**Comment by Rotzbua** [comment]
You have to enable c++**11** support. It's a compiler flag. I think that helps you to google it or ask adafruit how to enable c++11.

**Comment by Rotzbua** [comment]
Or take an older release of this library without c++11, have a look at the change log.
