### ISSUE TITLE
Unkown firmware Arduino MFRC522

### ISSUE THREAD

**Issue by lovevoice** [miguelbalboa/rfid#363]
Hello Everyone,
When I open Dump info in MFRC522 I get the following message and couldn't read the card. 
![image](https://user-images.githubusercontent.com/37422458/37493740-478d4d34-28a6-11e8-9cee-def6a284f5f0.png)

Would you please help?

Thank you in advance.

**Comment by Rotzbua** [comment]
See https://github.com/miguelbalboa/rfid#troubleshooting , do the points of "I don't get input from reader or WARNING: Communication failure, is the MFRC522 properly connected?".
If the problem is not solved you got a broken reader.
