### ISSUE TITLE
How to change RFID Card Security A key  &  B key

### ISSUE THREAD

**Issue by webinteger** [miguelbalboa/rfid#369]
I have change keys  at chip  from the factory (FFFFFFFFFFFFh),
from arduino uno + RC522,  give pls an example, thanks!

**Comment by Rotzbua** [comment]
There is a example, if i remember correctly...

**Comment by webinteger** [comment]
Where is example, show link, example

**Comment by Rotzbua** [comment]
Folder "examples"

**Comment by Krupson** [comment]
In which example sketch? I don't see such example that demonstrates writing keys in "examples" folder.

**Comment by umursengul** [comment]
From Arduino IDE;
File > Examples > Examples from Custom Libraries > MFRC522 > ...
You should find an example for this situation if I understand correctly.

**Comment by Krupson** [comment]
Yeah, but which one from MFRC522 examples? I have checked all of them and there is nothing about changing key A and key B - that's the point.

**Comment by iZhangHui** [comment]
@webinteger @Krupson Could you help to test my  PR #454  for change the default keys?
