### ISSUE TITLE
Can't get the library working

### ISSUE THREAD

**Issue by EstebPain** [miguelbalboa/rfid#375]
OS version: Win 10 64b v1709
Arduino IDE version: 1.8.5
MFRC522 Library version: 1.4
Arduino device: arduino uno R3
MFRC522 device: typical chinese clone.

My problem here is that the arduino sketch is not recognizing the library, it gives errors like this:
'Class MFRC522' has no member named 'PCD_Init'

The only way to get it working is using the library <deprecated.h> which gives an antenna range of 5 milimeters at most.

I have been trying to get the library working for two days, have seen several arduino libraries installation tutorials, I got it on the documents folder/Arduino/libraries/MFRC522 (wich is 779kb) and inside I can see that everything is there, but when I try out the code, it wont find any PCD, PICC, uid or anything from the library itself.

I'm more thatn open to suggestions.

**Comment by Rotzbua** [comment]
> My problem here is that the arduino sketch is not recognizing the library, it gives errors like this:
'Class MFRC522' has no member named 'PCD_Init'

This is problem with your local installation. Reinstall your IDE and library.

**Comment by EstebPain** [comment]
I have just reinstalled and the problem remains the same.
I downloaded everything again and installed the library.
