### ISSUE TITLE
MFRC522.h with UTFT_Button.h Bug

### ISSUE THREAD

**Issue by NelmanJayLouieVasquez** [miguelbalboa/rfid#378]
I'm using
 * OS version: Window 7
 * Arduino IDE version: 1.8.4
 * MFRC522 Library version: 1.4.0 
 * Arduino device: Arduino Mega 2560
 * MFRC522 device: https://www.aliexpress.com/item/1-Set-MFRC-522-RC-522-RC522-RFID-Wireless-IC-Module-S50-SPI-Writer-Reader-Card/32676126540.html?src=google&albslr=227945310&isdl=y&aff_short_key=UneMJZVf&source=%7Bifdyn:dyn%7D%7Bifpla:pla%7D%7Bifdbm:DBM&albch=DID%7D&src=google&albch=shopping&acnt=494-037-6276&isdl=y&albcp=1057917489&albag=48711713941&slnk=&trgt=387778277500&plac=&crea=en32676126540&netw=g&device=c&mtctp=&gclid=Cj0KCQjw8YXXBRDXARIsAMzsQuXSJQ6Sd-MEZ4egScvn7n1yDUpR6nUVlZGbQjjC4uyWNHJWYUGrqxQaAsFeEALw_wcB&gclsrc=aw.ds

When I used this `mfrc522.PCD_Init(); ` function, UTFT_Button can't click, the return value of `UTFT_Button.checkButtons` always -1 it means nothing.

If I used 1.3.5 or lower, there's no bug.

Here's my example. https://www.hiveworkshop.com/pastebin/4531ab0be0d337521d080c8cd089588f15680/

**Comment by Rotzbua** [comment]
```cpp
URTouch myTouch(6, 5, 4, 3, 2);
UTFT_Buttons myButtons(&myGLCD, &myTouch);
MFRC522 mfrc522(53, 5);
```

You used pin 5 twice. Rst pin must be mfrc exclusive.
