### ISSUE TITLE
using icsp header on arduino nano

### ISSUE THREAD

**Issue by TomW1605** [miguelbalboa/rfid#381]
is it posable to change the pins to use the icsp header on the arduino nano? i am hoping to use this as an upgrade to an existing project that is already using all the digital pins on my nano so i cant use the default pinout.

**Comment by TomW1605** [comment]
@Rotzbua i get that this is not a bug so can you please direct me to where i should be asking this question?

**Comment by Rotzbua** [comment]
#. It is a arduino question -> arduino forum or e.g. stackoverflow
#. Before you ask simply google or better look into the pinout schematics, it tells you what pins you have to use for isp
