### ISSUE TITLE
Ok with Arduino UNO but dont work with nano V3

### ISSUE THREAD

**Issue by cperquis** [miguelbalboa/rfid#386]
Hello, my name is Christophe and I have a little problem with Accescontrol Script for MFRC522 

### Step 1: Describe your environment

 * OS version: LinuxMint
 * Arduino IDE version: 1.8.5
 * MFRC522 Library version: MFRC522 Githubcommunity 1.3.6
 * Arduino device: Genuino Nano V3
 * MFRC522 device: RC522 Chinese card buy to Ebay
  
### Step 2: Describe the problem
Work perfectly with Genuino Uno

Don't Work with Genuino Nano
I use the same breaboard and the sames pins connected  (Typical pin layout used )

  
  
#### Observed Results:

 When the Nano start, the led blink (blue/red/green) with message "Waiting PICCs to be scanned" on console but when I scan a tag, it read the  first tag UID and Freeze.
it's impossible to scan another tag without restart the Nano

-------------------
TAG Maitre UID
20A37EA6
-------------------
Système OK
Attente lecture TAG
TAG UID:
1A37EA1
TAG Maitre reconnu - Mode programmation
I have 255 Enregistré dans l' EEPROM
Presentez TAG à enregister ou supprimer dans l' EEPROM
Présentez TAG Maitre pour sortir du Mode Programmation
-----------------------------
TAG UID:
26284C69

  
#### Expected Results:

I wish use the nano perfectly to integrate it to my project.
Thanks you too much for your Help !

**Comment by Rotzbua** [comment]
@cperquis Can you try 1.4.0?

**Comment by cperquis** [comment]
Hello,

I redid all the connectors and do hard reset to erase all registered tags.

All work perfectly.
Thank you for your kind assistance

.
