### ISSUE TITLE
RFID Cloner Question

### ISSUE THREAD

**Issue by AnthonyFuller** [miguelbalboa/rfid#387]
Quick question,

The RFID Cloner example:

https://github.com/miguelbalboa/rfid/blob/master/examples/RFID-Cloner/RFID-Cloner.ino

Do I just scan the card that i want to copy, then scan the card then it writes to it?

Thanks, Anthony.

**Comment by Rotzbua** [comment]
The description says:

>  * Copy the RFID card data into variables and then 
>  * scan the second empty card to copy all the date

So the answer is: yes.

**Comment by ebbeeh** [comment]
But it's not possible to scan a card in the options?

**Comment by Rotzbua** [comment]
> But it's not possible to scan a card in the options?

What do you mean with "scan a card in the options" ?

**Comment by ebbeeh** [comment]
the program gives you 3 options, but non of them scans the card

**Comment by Rotzbua** [comment]
The example is a community commit, so maybe the example is not perfect.

I guess:
> 1 scan
> 2 show
> 3 copy

Pull requests to improve (translation, description) the example are welcome.

**Comment by ebbeeh** [comment]
Thank you.
