### ISSUE TITLE
Volunteer to add documentation

### ISSUE THREAD

**Issue by richelbilderbeek** [miguelbalboa/rfid#393]
### Step 1: Describe your environment

 * OS version: Lubuntu newest version, 18.04 LTS (Bionic Beaver), with kernel: Linux winloos 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
 * Arduino IDE version: 2:1.0.5-dfsg2-4.1
 * MFRC522 Library version: all 
 * Arduino device: All
 * MFRC522 device: All
  
### Step 2: Describe the problem

For an Arduino course, I could not get this library to compile for the current version. I made [an Issue for that problem](https://github.com/richelbilderbeek/ArduinoCourse/issues/65) and started working back to earlier versions, as I suspected the cause would be the OS and our old computers. At v1.1.3 I got the library to be compiled successfully.

As this repository is the place to go for such an error, I would like to document it here, via a Pull Request.

#### Affected file(s) or example(s):
  
  * None
  
#### Steps to reproduce:

  1. sudo apt install arduino
  2. Download this library as a zip, this zip will be called `rfid-master.zip`
  3. Unzip that zip. A folder `rfid-master` will be created
  4. Rename that folder to `RFID`
  5. In the Arduino IDE, click `Import Library` and select the RFID folder. A warning about the dash in the name of the `RFID-Cloner` example appears
  6. Run any example, to get a compiler error
  7. It can be fixed by using v1.1.3
  
I volunteer to doucment this problem and solution, via a Pull Request. Just assign this Issue to me :-)

#### Observed Results:

  * What happened?  This could be a description, log output, screenshot, etc.

I could not find helpful documentation about this in the Troubleshooting section of this repository.
  
#### Expected Results:

  * What did you expect to happen?

To find helpful documentation about this.
  
#### Relevant Code:

```arduino
  // TODO(you): code here to reproduce the problem
  // No code is needed
```

**Comment by Rotzbua** [comment]
#392
