### ISSUE TITLE
Firmware Version: 0x1C = (unknown) Scan PICC to see UID, SAK, type, and data blocks...

### ISSUE THREAD

**Issue by Hotchongas** [miguelbalboa/rfid#400]
``

### Step 1: Describe your environment

 * OS version: Windows 10
 * Arduino IDE version: Arduino 1.8.5
 * MFRC522 Library version: 1.3.6
 * Arduino device: Arduino Uno
 * MFRC522 device: RFID Module
  
### Step 2: Describe the problem
    
       
A frimware Version unknown It always outputs in the serial monitor:

`Firmware Version: 0x1C = (unknown)
Scan PICC to see UID, SAK, type, and data blocks..`
.
Can someone help me...

**Comment by Rotzbua** [comment]
>Firmware Version: 0x1C

If you already done everthing in the troubleshooting section of the readme, then I guess your hardware has an error. Contact your supplier.

Best

**Comment by sridivya1** [comment]
Firmware Version: 0xEE = (unknown)
Scan PICC to see UID, SAK, type, and data blocks...
I am getting the above error. My version of mfrc522 is 1.4.2.

**Comment by nvatuan** [comment]
> Firmware Version: 0xEE = (unknown)

I had this exact problem with reported version 0xEE. I redid the soldering and it worked fine now. For future readers, maybe check your soldering again.

**Comment by novixe439** [comment]
I already resoldered it but it still doesn't work 😭

**Comment by novixe439** [comment]
Does it mean that my hardware is the problem? Pls help me I really need this for a project 🥺

**Comment by Rotzbua** [comment]
@novixe439 There is big help https://github.com/miguelbalboa/rfid#troubleshooting otherwise you have to contact your supplier.
