### ISSUE TITLE
working

### ISSUE THREAD

**Issue by awsmhemi** [miguelbalboa/rfid#401]
anyone plz explain me the working of these lines... This from rfid reader sample program.

 for (byte i = 0; i < mfrc522.uid.size; i++) 
  {
     Serial.print(mfrc522.uid.uidByte[i] < 0x10 ? " 0" : " ");
     Serial.print(mfrc522.uid.uidByte[i], HEX);
     content.concat(String(mfrc522.uid.uidByte[i] < 0x10 ? " 0" : " "));
     content.concat(String(mfrc522.uid.uidByte[i], HEX));
  }

**Comment by awsmhemi** [comment]
![screenshot 27](https://user-images.githubusercontent.com/25565297/42593087-1777186c-8569-11e8-98a8-41f9b5a5330e.png)

**Comment by Rotzbua** [comment]
Hi,
this is a programming question. Please ask in the arduino forum, stackoverflow or something else you prefer.
Best
