### ISSUE TITLE
A MIFARE PICC responded with NAK

### ISSUE THREAD

**Issue by fxhernandez87** [miguelbalboa/rfid#418]
Can anyone pls help, i've already tried to authenticate with both keys A and B, but there are 2 blocks that i cant rewrite.
when i dump the sector, this is what shows:
```
 1      7   00 00 00 00  00 00 19 67  8E 00 00 00  00 00 00 00  [ 0 1 1 ] 
          6   CE FF FF FF  31 00 00 00  CE FF FF FF  06 F9 06 F9  [ 1 1 0 ]  Value=0xFFFFFFCE Adr=0x6
          5   00 80 D4 44  00 00 00 00  00 00 00 00  00 00 00 00  [ 1 1 0 ]  Value=0x44D48000 Adr=0x0
          4   47 4F 4E 5A  41 4C 45 53  20 20 46 41  42 49 4F 20  [ 0 0 0 ] 
```
dont know what are these "Value=0xFFFFFFCE Adr=0x6" and " Value=0x44D48000 Adr=0x0".

Can anyone tell me what should i do to reset these blocks?

Thanks

**Comment by Rotzbua** [comment]
> A MIFARE PICC

Nobody can guess what kind of picc you have.

--> First add the environment information, see https://github.com/miguelbalboa/rfid/blob/master/.github/ISSUE_TEMPLATE.md
