### ISSUE TITLE
Changing the MFRC522 Receiver Gain

### ISSUE THREAD

**Issue by mdxs** [miguelbalboa/rfid#43]
Inspired by the _"Extend range for MFRC522 RFID Reader"_ discussion at http://forum.arduino.cc/index.php?topic=199983.0 I've played around a bit.

Initially, I followed the approach _"omersiar"_ described in that discussion: to alter the PCD_Init() implementation within the .cpp of the library. But somehow it didn't feel right... and the approach didn't seem to respect reserved/future bits either.

So, I reverted the library changes and found that the following works to set the Rx Gain to it's maximum value (which is documented to be some 48 dB; see 9.3.3.6 / table 98):

```
    mfrc522.PCD_Init();  // NOTE: unmodified initialization...
    // Enhance the MFRC522 Receiver Gain to maximum value of some 48 dB
    mfrc522.PCD_SetRegisterBitMask(mfrc522.RFCfgReg, (0x07<<4));
```

Note that this is done inside the sketch, within the regular setup. Perhaps one can also change it from within the main loop. Possibly cycling through the options by some button being pressed?

While above code works to maximize the Rx Gain, in order to minimize it... we need:

```
    mfrc522.PCD_Init();  // NOTE: unmodified initialization...
    // Reduce the MFRC522 Receiver Gain to minimum value of some 18 dB
    mfrc522.PCD_ClearRegisterBitMask(mfrc522.RFCfgReg, (0x07<<4));
    mfrc522.PCD_SetRegisterBitMask(mfrc522.RFCfgReg, (0x00<<4));
```

Note the bit mask clearing call, which (as the set register call) should avoid altering reserved/future bits. It seemed to be the cleanest way to do this.

Between minimum and maximum settings, you will notice a big difference (in centimetres: cm) in the distance at which the PICC is read. Now beware, newbie at play... and I've **NOT** tried all the bit patterns, but think this is on the right track and better than what the mentioned discussion described.

**Comment by albapa** [comment]
Hi, should there be a difference whether PCD_SetAntennaGain() is called before or after PCD_Init()? Thanks in advance.

**Comment by omersiar** [comment]
Should be, because when you call gain control it modify pcd's specific
register you should init before any other register change.
21 Tem 2015 16:25 tarihinde "albapa" <notifications@github.com> yazdı:

**Comment by albapa** [comment]
Thanks for your reply.

I was asking because in the original version the antenna gain was set in PCD_Init() *before* calling PCD_AntennaOn(). In the update, if you call PCD_SetAntennaGain() *after* PCD_Init(), this will naturally happen also *after* switching on the antenna.

I suppose my question really is whether setting the appropriate register corresponding to maximum gain should happen before or after switching on the antenna or it doesn't matter. Thanks!

**Comment by YIGITER-CLOAK-AND-DAGGER** [comment]
When I use the function in my code mfrc522.PCD_SetRegisterBitMask(mfrc522.RFCfgReg, (0x07<<4)) after initializing the reader The RFID reader will misread the codes for the RFID. It doesn't matter the level of gain. 20% of the time it reads it wrong. When I remove it there is no error. I have tested it with multiple types and the error persists.
