### ISSUE TITLE
Sudden 300ms lag spike in mfrc522.PICC_IsNewCardPresent()

### ISSUE THREAD

**Issue by Landfishy** [miguelbalboa/rfid#431]
This is blowing my mind. I am running an arduinoMega2560 with a standard ethernet shield and the RFID-RC522. I've been programming this little guy for several weeks, and had my program working, then all of a sudden I am getting a perfect, 300ms lag spike whenever I call mfrc522.PICC_IsNewCardPresent(). I thought I was going crazy because I rolled back to the version of the program I was working with that morning and it was also showing the lag spike. Then I replaced every component except the Mega (spare coming in the mail), and the issue persisted, even across a new RFID-RC522. Here is the feedback from millis() on each routine of my program...

> runCheckRFID entered >
Time is ============================== 384555ms
Time is ========IsNewCardPresent========== 384855ms
< runCheckRFID exited <
> runDisplayUpdate entered >
Time is ============================== 384859ms
> manageSFXtriggers entered >
Time is ============================== 384866ms
> runLEDChangeTracker entered >
Time is ============================== 384896ms
< runLEDChangeTracker exited <
<  runDisplayUpdate exited <
> handleInboundENET entered >
Time is ============================== 384908ms
< handleInboundENET exited <
> updateInputs entered >
Time is ============================== 384917ms
< updateInputs exited <
Time is ============================== 384923ms
> runModeControl entered >
Time is ============================== 384928ms
< runModeControl exited <
> runCheckRFID entered >
Time is ============================== 384934ms
Time is ========IsNewCardPresent========== 385234ms
< runCheckRFID exited <

If I enter a run mode that does not call mfrc522.PICC_IsNewCardPresent(), the program accelerates back up to its expected cycletime. We didn't even know it was doing this until all of our lighting systems suddenly started shuddering with a refresh rate of about 3Hz.

And here is the use of the function, in the routine...
`int runCheckRFID()
{
  if(DEBUGMODE)Serial.println("> runCheckRFID entered >");
  Serial.print("Time is ============================== "); Serial.println(millis());  
  //Check to see if there is not a new card; if not, just bail out of the subroutine.
  if ( ! mfrc522.PICC_IsNewCardPresent()){ Serial.print("Time is ========IsNewCardPresent=========== "); Serial.println(millis()); return;}
  if ( ! mfrc522.PICC_ReadCardSerial()) {Serial.print("Time is ========ReadCardSerial=========== "); Serial.println(millis()); return;}
}
`
Does anyone have any idea what is going on? I am absolutely confounded right now! D:

(By the way, I was running 1.3.6 and have updated to 1.4.1 and the issues persists.)

**Comment by Rotzbua** [comment]
duplicate #430
