### ISSUE TITLE
RFID/MRFC522 - Incompatible with certain manufacturer versions of MEGA2560 architecture

### ISSUE THREAD

**Issue by Landfishy** [miguelbalboa/rfid#434]
Tied into https://github.com/miguelbalboa/rfid/issues/430, which Rotzbua closed.

Oh its way, way more interesting. I have a slew of MEGA boards here and only some of them are exhibiting the behaviors described in that old issue. Theres a direct relationship to which brands are apparently affected, as fresh replacement boards from suspect brands immediately exhibited a 300ms delay when attempting to read, when others did not.

**Comment by Rotzbua** [comment]
You can still add new comments to closed issues.

About the mega boards: post a picture or which brands are affected by the delay.

The topic is not really relevant for this library because it is about the megas and not the mfrc522. That's the reason why I close this.
