### ISSUE TITLE
CloneUID does not work

### ISSUE THREAD

**Issue by Palacionis** [miguelbalboa/rfid#441]
The cloneUID does not read the card. Passing 1 or 3 to the serial monitor does nothing. Once I touch the cards nothing happens. I am trying to write UID to id card but so far none of the codes I've found on the internet really work. Does anyone have a working code in which I could clone a card or code where I could write my UID and then pass it to the card?

**Comment by Rotzbua** [comment]
Missing environment, no information about used card.
https://github.com/miguelbalboa/rfid/blob/master/.github/ISSUE_TEMPLATE.md
