### ISSUE TITLE
Add ESP-32 to library.properties to avoid warnings

### ISSUE THREAD

**Issue by tueddy** [miguelbalboa/rfid#443]
Hi,

MFRC522 runs perfectly fine on my ESP-32. ESP8266 seems already supported.
But i get a warning in Ardiono IDE (german here):

> 
WARNUNG: Bibliothek MFRC522 behauptet auf (avr, STM32F1, teensy, esp8266, samd) Architektur(en) ausgeführt werden zu können und ist möglicherweise inkompatibel mit Ihrem derzeitigen Board, welches auf (esp32) Architektur(en) ausgeführt wird.

To avoid the warning please add "esp32" as supported architecture.
Thank's and best
Dirk

**Comment by Rotzbua** [comment]
Ok, I am waiting for your pull request.
