### ISSUE TITLE
WeMos D1 Version 2015-08 Connection

### ISSUE THREAD

**Issue by daniesdk** [miguelbalboa/rfid#444]
Hi Michael and all users.

I have been working successfully with your RFID program (And well done with the project. Thank you so much)

I have recently got my hands on a Wemos D1 board. Not sure if it is a R1/R2, all I know is that it is a 2015-08 version.

Now, I have tried every possible Pin connection combinations and I still receive the following error:
"WARNING: Communication failure, is the MFRC522 properly connected?"
And then it won't scan at all.

Please can someone assist me with this? 
A pin connection layout and which pins I need to use in the coding?

And yes, I am quite new with the more advanced stuff of IOT so I do apologize in advance.

Thank you in advance.

**Comment by Rotzbua** [comment]
>  A pin connection layout and which pins I need to use in the coding?

Please read the readme:
https://github.com/miguelbalboa/rfid#pin-layout

> I have recently got my hands on a Wemos D1 board. Not sure if it is a R1/R2, all I know is that it is a 2015-08 version.

Wemos has a good wiki for pin layout and basic information.
https://wiki.wemos.cc

> Now, I have tried every possible Pin connection combinations and I still receive the following error: [..]

maybe you switched:
SPI MOSI | D7
SPI MISO | D6

try a other pin than 
RST/Reset | D3


If nothing works check soldering. Check mfrc module with arduino. There are a lot of bad mfrc modules.

Good look
