### ISSUE TITLE
reason for using & 0xFF for a mask in MFRC522.cpp 

### ISSUE THREAD

**Issue by ghost** [miguelbalboa/rfid#447]
### Step 1: Describe your environment

 * OS version: Linux 4.15.0-43 ubuntu 18.04
 * Arduino IDE version: 1.8.8
 * MFRC522 Library version: 1.4.3 
 * Arduino device: Teensy 3.2
 * MFRC522 device: rfid-rc522
  

This is about the code in ```MFRC522.cpp``` file on line 122 in function ```MFRC522::PCD_ReadRegister```

```byte mask = (0xFF << rxAlign) & 0xFF;```
  
Is the ```& 0xFF``` there for a reason?
Is it not redundant?

**Comment by Rotzbua** [comment]
> Is the & 0xFF there for a reason?

Yes, `(0xFF << rxAlign)` is internally processed in c as `int`. So we need to mask the int to a uint8_t / byte.

> Is it not redundant?

Yes and no. The type of `mask` is byte, so the size is truncated to 0xff implicit. But I am fine with a explicit truncate with `& 0xFF`. I guess in earlier versions `mask` was a different type.
