### ISSUE TITLE
Board won't read tags, but gets version

### ISSUE THREAD

**Issue by avaldes95** [miguelbalboa/rfid#450]
Using the firmware check gets me the proper firmware 0x92 = v2.0
However, it says that it has a "defect or unknown". It worked with a library fork from this that I found: https://github.com/ljos/MFRC522

I'm trying to not rewrite this code with the other library, so any solutions?

**Comment by Rotzbua** [comment]
https://github.com/miguelbalboa/rfid/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by avaldes95** [comment]
Windows 10
Arduino IDE 1.8.8
Release v1.4.1
Arduino Uno
RFID RC522

Problem: When I use the firmware check, the response is: 
Firmware 0x92 v2.0
Result: Defect or Unknown

https://github.com/miguelbalboa/rfid/blob/master/examples/firmware_check/firmware_check.ino

Then, I tried to run another one of the programs to try to scan a tag and it doesn't scan a tag or card that came with the package.

**Comment by Rotzbua** [comment]
Then the firmware of your chip is damaged or maybe you got a fake mfrc522. You can not fix that. You can compare the printing on your chip with known bad chips, see #428.

**Comment by avaldes95** [comment]
but it works with another library that is a branch of a previous release of this one

**Comment by Rotzbua** [comment]
The `firmware_check.ino` checks the firmware of the chip according to the official data sheet. If the check fails, there must be something wrong with your chip.

There are some fake chips which do not implement all functions of the genuine chip. The reported version was `0x12` maybe they now report version `0x92`.

It is possible that the older version of this library works with this fake chip because it do not use all functions of the genuine chip.

**Comment by jbarros35** [comment]
I need to know where to get the library which works. I don't need the "all functions for the real board" I only need to read tags!

**Comment by Maclec** [comment]
MFRC522 Digital self test
*****************************
Firmware Version: 0x91 = v1.0
-----------------------------
Only known versions supported
-----------------------------
Performing test...
-----------------------------
Result: DEFECT or UNKNOWN
 I am using RFID MFRC522 and  facing this type of problem . please help me , what can i do for my project.
