### ISSUE TITLE
Intermittent Functionality

### ISSUE THREAD

**Issue by avaldes95** [miguelbalboa/rfid#453]
### Step 1: Describe your environment

 * OS version: Windows 10
 * Arduino IDE version: 1.8.8
 * MFRC522 Library version: 1.4.3
 * Arduino device: UNO
 * MFRC522 device: MiFare RC522
  
### Step 2: Describe the problem

When using the firmware_check.ino and configuring it to my pins, the RFID works properly but eventually the connection goes bad.

When I press the RESET on my arduino or reload the program, sometimes it works or sometimes it doesn't.

I'm thinking that I should resolder it. Thoughts?

**Comment by Rotzbua** [comment]
> I'm thinking that I should resolder it. Thoughts?

Yes, it is a good idea.

 If you run firmware check and normal code you may observe bug #402.
