### ISSUE TITLE
Write Error

### ISSUE THREAD

**Issue by williamesp2015** [miguelbalboa/rfid#455]
I am using ESP32 with Arduino compiler and having problem writing to a generic MFRC522 
https://www.instructables.com/id/Arduino-RFID-Reader-MFRC522-Turorial/
I get this error:

Card UID: D0 EC ED 1B
PICC type: MIFARE 1KB
Authenticating using key A...
PCD_Authenticate() failed: Timeout in communication.
Card UID: D0 EC ED 1B
PICC type: MIFARE 1KB
Authenticating using key A...
PCD_Authenticate() failed: Timeout in communication.
Card UID: D0 EC ED 1B
PICC type: MIFARE 1KB
Authenticating using key A...
PCD_Authenticate() failed: Timeout in communication.
Card UID: D0 EC ED 1B
PICC type: MIFARE 1KB
Authenticating using key A...

PCD_Authenticate() failed: Timeout in communication.

**Comment by williamesp2015** [comment]
I tested all examples of writing example and I got the same timeout error. I also  reduced SPI speed but no difference. How to check if RFID Card is locked or unwritable?

**Comment by Rotzbua** [comment]
> I am using ESP32 with Arduino compiler and having problem writing to a generic MFRC522
https://www.instructables.com/id/Arduino-RFID-Reader-MFRC522-Turorial/

Your environment is not clear.

Please add the information according to the template:
https://github.com/miguelbalboa/rfid/blob/master/.github/ISSUE_TEMPLATE.md
