### ISSUE TITLE
Firmware Version: 0x15= (unknown)

### ISSUE THREAD

**Issue by adaiwa** [miguelbalboa/rfid#456]
Hey,
problem with 0x12 is well-know, but what about 0x15? Has anyone heard about it?

I bought RC522 with chip NXT TXD6080, connected to nodemcu v3, all connections looks fine:
SDA -> D2
SCK -> D5
MOSI -> D7
MISO ->D6
RST -> D4
and 3.3v with GND

after then i run firmware_check example and this show me version 0x15 unknow.

Any idea?

**Comment by Rotzbua** [comment]
Looks like this bad board: https://github.com/miguelbalboa/rfid/issues/428#issuecomment-429471060

> Any idea?

Contact seller / try to refund.

**Comment by lmmeng** [comment]
Hi @adaiwa;
Is the board working OK with other, functional examples?
If yes, I suppose the firmware_check example needs an update, to include the new board.

Just my 2 (euro)cents.
