### ISSUE TITLE
Add pin allocations in README.rst for Arduino Zero+SAMD boards

### ISSUE THREAD

**Issue by commonbreed** [miguelbalboa/rfid#459]
### Environment
 * OS version: macOS Mojave
 * Arduino IDE version: 1.8.9
 * MFRC522 Library version: v1.4.3 
 * Arduino device: Genuino Zero (Arduino Zero)
 * MFRC522 device: RFID-RC522

I have thus far been unable to get this library working with the Arduino Zero, primarily because the pin allocations are not present in the table in the README.

Could these please be added.

**Comment by Rotzbua** [comment]
Connecting SPI devices shouldn't be so hard. Pull requests to update doc are welcome.

**Comment by Rotzbua** [comment]
Closed inactive.
