### ISSUE TITLE
LIBRARY RFID-MASTER (Problem to compile)

### ISSUE THREAD

**Issue by mariaguarin09** [miguelbalboa/rfid#460]
* OS version:  Windows Operative system of 64 bits .
 * Arduino IDE version: 1.8.9 .
 * rfid-master Library version: 1.4.4 
 * Arduino device: None.. I´m using the Board LinkIT ONE.
 * rfid-master device: RFID RC522.
  
### Step 2: Describe the problem
Hi! I'm wondering if you can help me with a problem I´m using the library rfid-master (version 1.4.4) to work with an RFID RC522 and the board IinkIT ONE, I have compile the code but there is a problem with the architecture of the library, because linkIT ONE works with ARM. The code error is this:

ATTENTION: The library  rfid-master pretends to run  about architecture(s) (avr, STM32F1, teensy, esp8266, samd) and it can't be incompatible with your current card which runs on architecture (s) (arm).
In file included from W:\Users\Adriana\Documents\Arduino\libraries\rfid-master\src/MFRC522.h:78:0,
                 from W:\Users\Adriana\Documents\Arduino\libraries\rfid-master\examples\DumpInfo\DumpInfo.ino:37:
W:\Users\Adriana\Documents\Arduino\libraries\rfid-master\src/require_cpp11.h:9:2: error: #error "This library needs at least a C++11 compliant compiler, maybe compiler argument for C++11 support is missing or if you use Arduino IDE upgrade to version >=1.6.6"
 #error "This library needs at least a C++11 compliant compiler, maybe compiler argument for C++11 support is missing or if you use Arduino IDE upgrade to version >=1.6.6"
  ^
exit status 1
Error compiling for the card LinkIt ONE.

#### Affected file(s) or example(s):
 
It doesn't work... And the pins configurations are all correct.
  
#### Relevant Code:

```c++
  // TODO(you): code here to reproduce the problem
```

**Comment by Rotzbua** [comment]
> This library needs at least a C++11 compliant compiler, maybe compiler argument for C++11 support is missing or if you use Arduino IDE upgrade to version >=1.6.6

You need `C++11 support`. Maybe you find in the internet how to or ask the `LinkIT ONE` support how to enable.
