### ISSUE TITLE
No NDEF format support

### ISSUE THREAD

**Issue by hutje** [miguelbalboa/rfid#463]
### Step 1: Describe your environment

 * OS version:   Arduino IDE 
 * Arduino IDE version: master
 * MFRC522 Library version: master
 * Arduino device: uno
 * MFRC522 device: RFID-RC522
  
### Step 2: Describe the problem
The library doesn't support NDEF format. This is a normal format for writing to a NFC tag

#### Observed Results:

  reading auth error when dumpinfo
  
#### Expected Results:

  I expect to be able to read the dump info. Maybe even decode the NDEF.

**Comment by Rotzbua** [comment]
NDEF is not supported and not planned for the future.

The https://github.com/miguelbalboa/rfid/wiki mention a extension https://github.com/Gargantuanman/MFR522_NDEF .

The data on a tag is always protected by a key. The dumpinfo uses fff..f as key. Maybe there is a different key used by the NDEF specification.
