### ISSUE TITLE
Is there any example for ISO4443-4?

### ISSUE THREAD

**Issue by bitkinbitki** [miguelbalboa/rfid#466]
Hi,

Is there any example for ISO4443-4 standarts? How can I use extended functions in MFRC522Extended.c ?

**Comment by Rotzbua** [comment]
> Is there any example for ISO4443-4 standarts?

Not, only in https://github.com/JPG-Consulting/rfid-desfire

> How can I use extended functions in MFRC522Extended.c ?

The "extended" was developed by JPG-Consulting to use it in:
https://github.com/JPG-Consulting/rfid-desfire

**Comment by Rotzbua** [comment]
inactive -> closed
