### ISSUE TITLE
Cards not added everytime

### ISSUE THREAD

**Issue by Dogy007** [miguelbalboa/rfid#475]
Hi!
I just tested the example "AccessControl". I did not change anything from the code but yet encountered a problem.  

I have noticed that sometimes card's don't get added OR removed. I have yet to figure out a pattern.

Below is the output from the serial monitor, i hope i described it good enough.

Scanned PICC's UID:
96DD14B9
You shall not pass
Scanned PICC's UID:
16133AB9
Hello Master - Entered Program Mode
I have 8 record(s) on EEPROM
Scan a PICC to ADD or REMOVE to EEPROM
Scan Master Card again to Exit Program Mode
-----------------------------
Scanned PICC's UID:
96DD14B9
I do not know this PICC, adding...
Succesfully added ID record to EEPROM
-----------------------------
Scan a PICC to ADD or REMOVE to EEPROM
Scanned PICC's UID:
16133AB9
Master Card Scanned
Exiting Program Mode
-----------------------------
Scanned PICC's UID:
96DD14B9
You shall not pass
-----------------------------

**Comment by Rotzbua** [comment]
Please use existing issue #403
