### ISSUE TITLE
Connecting Arduino IDE to the database?

### ISSUE THREAD

**Issue by MariaMaria97** [miguelbalboa/rfid#479]
Hello Dr.miguelbalboa
I want to connect the arduino to Mysql server so that the UID of the tag displayed on the serial monitor will be automatically inserted in my table from my database: I'm using Nodemcu esp8266, an RFID reader MFRC522 and arduino IDE so I wrote this program where I used the example DumpInfo:
#include <ESP8266WiFi.h>           // Use this for WiFi instead of Ethernet.h
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>
#include <SPI.h>
#include <MFRC522.h>

#define RST_PIN         D2          // Configurable, see typical pin layout above
#define SS_PIN          D4         // Configurable, see typical pin layout above

IPAddress server_addr(192,168,43,144);  // IP of the MySQL *server* here
char user[] = "*******";              // MySQL user login username
char password[] = "*****";        // MySQL user login password

// Sample query
char INSERT_SQL[] = "INSERT INTO rfiddata.tag (tag_id) VALUES ()";

// WiFi card example
char ssid[] = "******";         // your SSID
char pass[] = "*****";     // your SSID Password

WiFiClient client;                 // Use this for WiFi instead of EthernetClient
MySQL_Connection conn(&client);
MySQL_Cursor* cursor;

MFRC522 mfrc522(SS_PIN, RST_PIN);  // Create MFRC522 instance

void setup() {
	Serial.begin(115200);		// Initialize serial communications with the PC
	while (!Serial);		// Do nothing if no serial port is opened (added for Arduinos based on ATMEGA32U4)
  // Begin WiFi section
  Serial.printf("\nConnecting to %s", ssid);
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  // print out info about the connection:
  Serial.println("\nConnected to network");
  Serial.print("My IP address is: ");
  Serial.println(WiFi.localIP());

  Serial.print("Connecting to SQL...  ");
  if (conn.connect(server_addr, 3306, user, password))
    Serial.println("OK.");
  else
    Serial.println("FAILED.");
  
  // create MySQL cursor object
  cursor = new MySQL_Cursor(&conn);
  
  if (conn.connected())
    cursor->execute(INSERT_SQL);
    
	SPI.begin();			// Init SPI bus
	mfrc522.PCD_Init();		// Init MFRC522
	mfrc522.PCD_DumpVersionToSerial();	// Show details of PCD - MFRC522 Card Reader details
	Serial.println(F("Scan PICC to see UID, SAK, type, and data blocks..."));
}

void loop() {
	// Reset the loop if no new card present on the sensor/reader. This saves the entire process when idle.
	if ( ! mfrc522.PICC_IsNewCardPresent()) {
		return;
	}

	// Select one of the cards
	if ( ! mfrc522.PICC_ReadCardSerial()) {
		return;
	}

	// Dump debug info about the card; PICC_HaltA() is automatically called
	mfrc522.PICC_DumpToSerial(&(mfrc522.uid));
}

the serial monitor shows me that connexion between arduino and mysql server is okey and I can see the tag id successfully on my serial monitor, but please how can I insert this tag uid into my table called "tag" which is present in the my database called "rfiddata" ??
Thanks.

**Comment by Rotzbua** [comment]
For coding questions please use a arduino/esp communication platform. The issue section is *only* for problems in the library code.
