### ISSUE TITLE
Use only GPIO rising edge interruption ，there is a problem

### ISSUE THREAD

**Issue by tutuwin** [miguelbalboa/rfid#481]
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6348
load:0x40078000,len:11304
load:0x40080400,len:6700
entry 0x40080764
I (29) boot: ESP-IDF v4.0-dev-667-gda13efc17-dirty 2nd stage bootloader
I (29) boot: compile time 02:08:46
I (30) boot: Enabling RNG early entropy source...
I (36) boot: SPI Speed      : 40MHz
I (40) boot: SPI Mode       : DIO
I (44) boot: SPI Flash Size : 4MB
I (48) boot: Partition Table:
I (51) boot: ## Label            Usage          Type ST Offset   Length
I (59) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (66) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (74) boot:  2 factory          factory app      00 00 00010000 00100000
I (81) boot: End of partition table
I (85) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x07f18 ( 32536) map
I (106) esp_image: segment 1: paddr=0x00017f40 vaddr=0x3ffb0000 size=0x01dc8 (  7624) load
I (109) esp_image: segment 2: paddr=0x00019d10 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /home/linux/esp32/esp-idf/components/freertos/xtensa_vectors.S:1779

I (115) esp_image: segment 3: paddr=0x0001a118 vaddr=0x40080400 size=0x05ef8 ( 24312) load
I (133) esp_image: segment 4: paddr=0x00020018 vaddr=0x400d0018 size=0x12a98 ( 76440) map
0x400d0018: _flash_cache_start at ??:?

I (160) esp_image: segment 5: paddr=0x00032ab8 vaddr=0x400862f8 size=0x01a28 (  6696) load
0x400862f8: xTimerGenericCommand at /home/linux/esp32/esp-idf/components/freertos/timers.c:428

I (168) boot: Loaded app from partition at offset 0x10000
I (168) boot: Disabling RNG early entropy source...

**Comment by Rotzbua** [comment]
Missing minimum required information of template: https://github.com/miguelbalboa/rfid/blob/master/.github/ISSUE_TEMPLATE.md
