### ISSUE TITLE
Frequency change

### ISSUE THREAD

**Issue by tt1604** [miguelbalboa/rfid#484]
### Step 1: Describe your environment

 * OS version: windows 7 ultimate
 * Arduino IDE version: 1.8.9
 * MFRC522 Library version: 1.4.4
 * Arduino device: Mega 2560
 * MFRC522 device: RFID-RC522
  
### Step 2: Describe the problem
Is it possilbe to change the frequency?? I want to read diveces they use DIN / ISO 11784/11785
They use frequency 125/134,2 kHz

**Comment by Rotzbua** [comment]
impossible
