### ISSUE TITLE
Reading from Sector Trailer, Key A always return 0x00 00 00...

### ISSUE THREAD

**Issue by steelywing** [miguelbalboa/rfid#487]
* MFRC522 Library version: 1.4.4
 * MFRC522 device: MFRC522
  
When I read from Sector Trailer, the Key A always return 0x00 00 00 00 00 00, but the correct Key A is 0xFF FF FF FF FF FF, is it normal? Only the access bits and Key B return normal.

I have tried several card, the Key A also return 0x00.

**Comment by Rotzbua** [comment]
Dump returns the raw data. The key is stored in a different way according to the tag specification. Normal mifare card inverts data at some points.
