### ISSUE TITLE
fail to authenticate with keyB 

### ISSUE THREAD

**Issue by Rita-GE** [miguelbalboa/rfid#490]
Step 1: Describe your environment

 * OS version: win10
 * Arduino IDE version: 1.8.5
 * MFRC522 Library version: 1.4.4
 * Arduino device: arduino UNO R3
 * MFRC522 device: RFID-RC522
  
### Step 2: Describe the problem
First of all,thanks to your library.
Here is the problem:
#### Affected file(s) or example(s):
  
  * MifareClassicValueBlock.ino  (refer)
  
#### Steps to reproduce:

  1. access bit:g[0] = 000 g[1] = 110 g[2] = 000 g[3] = 001
           mfrc522.MIFARE_SetAccessBits(&trailerBuffer[6], 0, 6, 0, 1);
  2. keyA and keyB = FF FF FF FF FF FF
  3. wirte 100 into a value block:
            mfrc522.MIFARE_SetValue(valueBlock, 100)
  
#### Relevant Code:
```cpp
status = mfrc522.PCD_Authenticate(MFRC522::PICC_CMD_MF_AUTH_KEY_B, (sector * 4 + 3), &key, &(mfrc522.uid));
  if (status != MFRC522::STATUS_OK) {
    Serial.print(F("PCD_Authenticate() failed: "));
    Serial.println(mfrc522.GetStatusCodeName(status));
    return;
  }

  status = mfrc522.MIFARE_SetValue(valueBlock, 100);
  if (status != MFRC522::STATUS_OK) {
    Serial.print(F("mifare_SetValue() failed: "));
    Serial.println(mfrc522.GetStatusCodeName(status));
    return;
  }
```

#### Observed Results:

  * MF1 S50 success to anthenticate to sector2 with keyB,while MF1 S50 EV1 failed.
  * Does MF1S50EV1 can not antheticate with keyB?

**Comment by Rotzbua** [comment]
@Rita-GE Any update? Otherwise I close this.
