### ISSUE TITLE
Firmware Version: 0x12 =counterfeit chip

### ISSUE THREAD

**Issue by Mhaiii** [miguelbalboa/rfid#501]
### Step 1: Describe your environment

 * OS version: 10
 * Arduino IDE version: 1.8.7
 * MFRC522 Library version: 1.4.5 
 * Arduino device: Uno
 * MFRC522 device: RFID-RC522
  
#### Affected file(s) or example(s):
  
  * Filename 1
  * Filename 2
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

```c++
  // TODO(you): code here to reproduce the problem
```

**Comment by Rotzbua** [comment]
No content. Closed.
