### ISSUE TITLE
Increase Antenna Range 

### ISSUE THREAD

**Issue by troglodisme** [miguelbalboa/rfid#502]
I am trying to increase the range of my reader using the library feature PCD_SetAntennaGain

I have followed this comment but can't get any improvement https://github.com/miguelbalboa/rfid/pull/47#issuecomment-285860139

Has somebody else managed to see an improvement in range adding an arduino Sketch change? Could you please share your examples?

Many thanks

**Comment by Rotzbua** [comment]
The improvement by increasing the antenna gain is not huge. More like 0.5 to 1 cm, which is only useful if the reader is covered by a case. For more range you need a different module (eg. wiegand).
