### ISSUE TITLE
When detect card wake up other cpu(Ardunio,Esp12,Esp32) ??

### ISSUE THREAD

**Issue by honestrock** [miguelbalboa/rfid#506]
Hello Did any one try wake up board from mfrc522 when detect card ?

I want to make door open with battery powered.

**Comment by Rotzbua** [comment]
To the best of my knowledge, that's not possible. The mfrc522 can not detect a card without a running and connected mcu.

For your use case add an button which temporarily activates your system and shutdown it automatically.
