### ISSUE TITLE
all RFID cards and fobs are clonables? 

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [miguelbalboa/rfid#507]
what is the difference between these CARDS?
MIFARE 1KB 
PICC type: PICC compliant with ISO/IEC 14443-4

someone told me this one: PICC type: MIFARE 1KB it is clonable with this machine:

https://www.amazon.co.uk/ACR122U-Contactless-Reader-Writer-5xMifare/dp/B00GYPIZG6/ref=pd_sim_229_3/258-8680719-6012845?_encoding=UTF8&pd_rd_i=B00GYPIZG6&pd_rd_r=2a7c1fb5-92ca-4605-9275-d524ff53b48f&pd_rd_w=77IpR&pd_rd_wg=sUza9&pf_rd_p=2fd67464-3829-4391-8747-f4fac7516a6d&pf_rd_r=GB39EJ2G1XFF3JRX9WBD&psc=1&refRID=GB39EJ2G1XFF3JRX9WBD

and this one it is encrypted: PICC type: PICC compliant with ISO/IEC 14443-4

could you guys tell me the difference between them? also how can I include a password or encrypt a card? any suggestions how I start?

how can make this card blocked to not be cloned?

is that what i am looking for? https://www.instructables.com/id/TouchPass-RFID-Password-Entry/

**Comment by Rotzbua** [comment]
The issue tracker is only about the library. Your intentions suggest the suspicion of breaking regulations or the law. For those reasons closed.
