### ISSUE TITLE
Making ReadUidMultiReader.ino works

### ISSUE THREAD

**Issue by danbraik** [miguelbalboa/rfid#527]
* OS version: Linux
 * Arduino IDE version: 1.8.13
 * MFRC522 Library version: 1.4.7
 * Arduino device: Uno
 * MFRC522 device: RFID-RC522 from AZ

Hello !

I was trying to make the example ReadUidMultiReader.ino  works with fiability.
It seems that the problem come from 
`#define SS_1_PIN        10 `

because it is used as SS for Arduino Uno to known that it is a slave SPI (https://www.arduino.cc/en/reference/SPI)

So I used another pin and just add in the setup:
`pinMode(10, OUTPUT);`

and it seems to work.

I am not sure if this is correct solution. Can someone can test it and corroborate my observation please ?

Best regards,

**Comment by Rotzbua** [comment]
there is already a huge topic #290
