### ISSUE TITLE
Change UID

### ISSUE THREAD

**Issue by Max16205** [miguelbalboa/rfid#530]
### Step 1: Describe your environment

 * OS version: Windows 10
 * Arduino IDE version: 1.8.13
 * MFRC522 Library version: Master
 * Arduino device: UNO
 * MFRC522 device: RFID RC522
  
### Step 2: Describe the problem
I write the UID in the Change UID file example: 0x1E, 0xD3, 0xAB, 0x78 but when I put my card on it says:

"Card did not respond to 0x40 after HALT command. Are you sure it is a UID changeable one?
Error name: Timeout in communication.
Activating the UID backdoor failed. "

#### Affected file(s) or example(s):
  
  * Filename 1: Change UID
  * Filename 2: RFID cloner
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, screenshot, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

```c++
  // TODO(you): code here to reproduce the problem
```

**Comment by Rotzbua** [comment]
You can not change the uid of normal cards as the error mentioned. Maybe it is a "magic card v2" then use  #448 or #522.
