### ISSUE TITLE
Will this library work with this RFID RC522 module ?

### ISSUE THREAD

**Issue by adrianTNT** [miguelbalboa/rfid#531]
Hello.
My RFID RC522 module looks like this:

![RFID RC522](https://user-images.githubusercontent.com/11273076/93026705-b1231f00-f610-11ea-9e15-7278e1e2e099.jpg)

The pinouts are labeled: `NRST, GND, SWIM, VCC` and `GND, RX, TC, VCC`
I cannot find any documenation, prodocol it uses, product name, etc, nothing :/

- Does anyone know what interface is this ? 
- And does this work with this library ?
- Could it write too or it is just for reading RF ?

Thank you.

**Comment by Rotzbua** [comment]
>  I cannot find any documenation, prodocol it uses, product name, etc, nothing :/

That is the worst case. 💥 

Your mentioned labels let me suggest i2c as supported protocol, which is not supported by this library. You can find libraries with i2c by github search or my untested fork, see #522.
