### ISSUE TITLE
MFRC522.h:22:26: error: 'SPI_CLOCK_DIV4' was not declared in this scope

### ISSUE THREAD

**Issue by maximus1127** [miguelbalboa/rfid#544]
### Step 1: Describe your environment

 * OS version: Windows 10
 * Arduino IDE version: 1.8.12
 * MFRC522 Library version: 1.4.7 
 * Arduino device: Nano 33 BLE Sense
 * MFRC522 device: RFID-RC522
  
### Step 2: Describe the problem

When loading the library and selecting an example sketch, I'm getting the error of "MFRC522.h:22:26: error: 'SPI_CLOCK_DIV4' was not declared in this scope". Everything is completely stock, the library was downloaded and imported straight into the editor, the example was selected without editing any code or anything. I can't even upload it to the nano as the compile failed with this error. I have also downgraded my IDE to version 1.6.x as the main page of the library states it's compatible with that version and I still get the same error.

  
#### Steps to reproduce:

  1. Import library
  2. Select example sketch "read NUID"
  3. compile and wait for pretty red text

**Comment by Rotzbua** [comment]
`SPI_CLOCK_DIV4` should be defined by the board.
What version and board implementation do you use for the Nano 33 BLE Sense ? Look it up at the board manager in the arduino ide.
Thanks

**Comment by maximus1127** [comment]
![image](https://user-images.githubusercontent.com/31026284/103225507-a8b8d080-48ef-11eb-98e8-1589975a8107.png)

I'm using the "Arduino Nano 33 BLE" board

**Comment by Rotzbua** [comment]
## Solution

Set compiler flag to overwrite with your values according to your board: `MFRC522_SPICLOCK `

## Simple Workaround

* Goto your local copy and change line:
https://github.com/miguelbalboa/rfid/blob/ea10e8a21963cb603167892cce37eab40f7a1bc6/src/MFRC522.h#L22
* Replace `SPI_CLOCK_DIV4` with `0`

## Longterm Solution

Would be to add the constants as compatibility to the board library.

**Comment by Rotzbua** [comment]
Solved by 34086ad99a86ff381dc3c4fd2454a6b7b8c3b78d
