### ISSUE TITLE
AccessControl.ino doesn't seem to work on esp32

### ISSUE THREAD

**Issue by 1orz** [miguelbalboa/rfid#549]
* Arduino IDE version:1.8.14
 * MFRC522 Library version: master-branch
 * Arduino device: ESP32 (ESP WROOM 32)
 * MFRC522 device: _____
  
Such as the title，AccessControl.ino doesn't seem to work on esp32， 
I'm not sure it has to do with abandoning EEPROM and switching to NVS in esp32.

In the test environment，Although it has been shown that "Succesfully added ID record to EEPROM", it will not take effect when the card is read again it  shown following message： “You shall not pass”，There seems to be no successful save uid in EEPROM

How to use it in esp32 correctly?

**Comment by Rotzbua** [comment]
It is a example.
It is simple.
It is not secure. 
It is only for Arduino boards with EEPROM.
There is a esp project which does "access control", use search to find.
