### ISSUE TITLE
Restart MRFC522 fails after hard power down

### ISSUE THREAD

**Issue by Oegtsgeest** [miguelbalboa/rfid#550]
OS version: _W10____
 * Arduino IDE version: 1.8.12
 * MFRC522 Library version:  v1.4.8
 * Arduino device: SAMD21 adafruitfeather M0
 * MFRC522 device: RFID-RC522
 * 
Tried to save power by switching off and on when required.
I used following code:
```c++
 if (selectionReceived == 700)   // power down
   {
    pinMode(RST_MRFC_PIN, OUTPUT);
    digitalWrite(RST_MRFC_PIN, LOW);        // hard power down of RFID board 
   }
if (selectionReceived == 701 )   // power up again
   { 
     digitalWrite(RST_MRFC_PIN, HIGH);                        
     mfrc522.PCD_Init();                    // Init MFRC522 ; Power up  RFIDoard 
   }
```
The unit powers down because I see the current dropping by approx 20mA. 
The restart does not work. Do I use the right code? Or is this a bug?
Help is very much appreciated.

**Comment by Rotzbua** [comment]
idk, but there is already a big thread about power saving techniques #269
