### ISSUE TITLE
Problem for presence tag

### ISSUE THREAD

**Issue by umbertoge** [miguelbalboa/rfid#553]
Hi
i test library for rc522....
but i have problem with command for read tag in the zone.....

if i call this routine, the answer (return) with tag on the antenna is in sequence 00,02,00,02,00,02
but with tag in the rfid signal, the answer muste be always 00,00,00,00,

why?
thanks

/**
 * Returns true if a PICC responds to PICC_CMD_REQA.
 * Only "new" cards in state IDLE are invited. Sleeping cards in state HALT are ignored.
 * 
 * @return bool
 */
bool MFRC522::PICC_IsNewCardPresent() {
	byte bufferATQA[2];
	byte bufferSize = sizeof(bufferATQA);

	// Reset baud rates
	PCD_WriteRegister(TxModeReg, 0x00);
	PCD_WriteRegister(RxModeReg, 0x00);
	// Reset ModWidthReg
	PCD_WriteRegister(ModWidthReg, 0x26);

	MFRC522::StatusCode result = PICC_RequestA(bufferATQA, &bufferSize);
	return (result == STATUS_OK || result == STATUS_COLLISION);
} // End PICC_IsNewCardPresent()

**Comment by Rotzbua** [comment]
1. Environment information?
2. Return value of `02` on a bool func?
