### ISSUE TITLE
Does exist possibility to read full dump for all mifare cards? 

### ISSUE THREAD

**Issue by Rombersoft** [miguelbalboa/rfid#557]
I want to read all dump (array bytes for each block) in order to parce it and extract PAN number credit card. It is real to do or not?

**Comment by Rombersoft** [comment]
Great! Have a nice last year!

**Comment by Rotzbua** [comment]
@Rombersoft As mentioned in the issue template, this issue tracker is just for bugs. If you have questions go to a forum. It is sad that I have to waste my unpayed free time with spam.
