### ISSUE TITLE
Library Doesn't Support SoftSPI

### ISSUE THREAD

**Issue by kshitijgarg2609** [miguelbalboa/rfid#564]
@Rotzbua , Please can you give the support for SoftSPI of DigitalIO, as I am unable to use other SPI device like SD card adapter along with RFID.

**Comment by kshitijgarg2609** [comment]
@ricardojlrufino , Please can you give the support for SoftSPI of DigitalIO, as I am unable to use other SPI device like SD card adapter along with RFID.

**Comment by kshitijgarg2609** [comment]
> @Rotzbua , Please can you give the support for SoftSPI of DigitalIO, as I am unable to use other SPI device like SD card adapter along with RFID.

**Comment by Rotzbua** [comment]
Plz use search next time.
Try code of #499
