### ISSUE TITLE
ESP32 Httpclient get method works, but not with mfrc522

### ISSUE THREAD

**Issue by erwan33fr** [miguelbalboa/rfid#565]
ESP32 or ESP8266

It seems that there is an incompatibility between the mfrc522 library and the method http.get from HTTPClient.h ?

https://forum.arduino.cc/t/esp32-httpclient-get-method-works-but-not-with-mfrc522/881640

**Comment by Rotzbua** [comment]
> It seems that there is an incompatibility 

No. Most ppl have bugs in their code.

**Comment by erwan33fr** [comment]
ok thanks
