### ISSUE TITLE
Example Code Bug

### ISSUE THREAD

**Issue by hackintoshlover** [miguelbalboa/rfid#567]
### Step 1: Describe your environment

 * OS version: Windows 7
 * Arduino IDE version: 1.8.13
 * MFRC522 Library version: Latest Master Version
 * Arduino device: UNO
 * MFRC522 device: v2.0
  
### Step 2: Describe the problem

I am trying to use the inbuilt library example code Access Control
The program behaves weird
It adds master card as expected
But while adding user card it does not work
1. It does not save more than two unknown cards in EEPROM, moreover only the first save data is correct after that all are incorrect, it says successfully added PICC card, but upon scanning says card not found.
2. Automatically overwrites EEPROM with same card data multiple times.

#### Affected file(s) or example(s):
  
Access Control
  
#### Steps to reproduce:

Connect mfrc522 to arduino uno and scan cards

#### Observed Results:

Does not work properly
  
#### Expected Results:

  As explained in the example
  
#### Relevant Code:

Access Control Example in the library mfrc522

I am attaching my serial monitor output for access control example and eeprom data read below
Kindly help
![Screenshot (51)](https://user-images.githubusercontent.com/40655406/127635634-dde33a44-2e52-4562-94e6-f8c4e7b9d8ba.png)
![Screenshot (41)](https://user-images.githubusercontent.com/40655406/127635635-7beb729f-83f8-421a-a642-e18cea045053.png)
![Screenshot (42)](https://user-images.githubusercontent.com/40655406/127635637-d8056be2-6079-4f54-b8f1-435cf8a2ff26.png)
![Screenshot (43)](https://user-images.githubusercontent.com/40655406/127635639-13098c94-99b6-41b4-b9d6-5b23a59d902a.png)
![Screenshot (44)](https://user-images.githubusercontent.com/40655406/127635640-e7aa25ba-5cf0-4a76-a016-7ccbb6b39f69.png)
![Screenshot (45)](https://user-images.githubusercontent.com/40655406/127635642-143ace61-19b6-42b5-9ccb-d0fa04a075d2.png)
![Screenshot (46)](https://user-images.githubusercontent.com/40655406/127635643-52e3d608-38a6-4f7b-b924-48fe098983a7.png)
![Screenshot (47)](https://user-images.githubusercontent.com/40655406/127635646-c7b0250d-04ba-4632-a278-32971f4c8c7a.png)
![Screenshot (48)](https://user-images.githubusercontent.com/40655406/127635648-3a51eeb1-3d68-4179-8084-1f8ce5a24591.png)
![Screenshot (49)](https://user-images.githubusercontent.com/40655406/127635649-43531321-b823-45ef-943d-b89d352ef34b.png)
![Screenshot (50)](https://user-images.githubusercontent.com/40655406/127635652-a5855c34-a5a5-4d1f-a81d-bc070dc51d4e.png)

**Comment by Rotzbua** [comment]
Hi hackintoshlover,
thanks for the detailed report 👍  .
Sadly there are issues #403 with this example since it was added to the repository years ago.
Sorry I don't have a satisfactory solution than to remove the example so as not to confuse more people.
Best wishes
