### ISSUE TITLE
Not working on Teensy 3.1

### ISSUE THREAD

**Issue by Powder** [miguelbalboa/rfid#57]
Hi,
I cannot get the library to work with a Teensy 3.1. Seems like other people have this problem [as well](http://forum.pjrc.com/threads/25596-Teency-3-1-Compatibility-with-MFRC522-RFID-Library).
The library works fine on an Arduino Leonardo.

May it be possible, that this has something to do with the fact that Teensy 3.1 runs on 32bit?

Here is a quote from Paul, one of the Teensy-Devs on that matter:

>I can tell you there are 3 common issues with 8 bit code porting to 32 bit platforms. The most common is putting 2 bytes from I2C into a 16 bit signed integer (common with motion sensors). A similar issue involves passing data through int pointers, where the pointer is initialized with the address of a 16 bit variable (eg, the variable is int16_t but the function's pointer is "int*").
The third issue involves using structs as data templates, where an array of bytes is access as a struct (usually though a pointer, initialized with the array address). On 8 bit AVR, structs are always packed together. But on 32 bit platforms, often the compiler will align the elements of the struct to 32 bit boundaries, which greatly improves performance, but it leaves small gaps in memory between the items in the struct. The packed attribute tells the compiler to pack the data together, the same as if it were on an 8 bit platform.
This library appears to use that technique, where data is received from the card into a byte array, then a struct pointer is initialized to the address of the array. That's why I suggested trying the packed attribute in reply #14. Please give it a try and let me know if it solves the problem?

**Comment by lberezy** [comment]
What's the current status of this?

I'm currently using this with a Teensy 3.1 board and it compiles and runs, but when a tag is bought near the reader it appears to dump the first few bytes and then go into a loop of `MIFARE_Read() failed: Timeout in communication.
`.

I had a look back through the forks and commit history, but couldn't find anything Teensy 3.1 related.
I did note, however, that the Teensy 3.1 is mentioned in the readme.
