### ISSUE TITLE
Issues using the library with an esp32 (Wemos lolin 32 lite)

### ISSUE THREAD

**Issue by syntaxbullet** [miguelbalboa/rfid#575]
* OS version:  Windows 10 19043
 * Arduino IDE version: using PlatformIO
 * MFRC522 Library version: 1.4.10
 * Arduino device: using Wemos ESP32 lolin lite 
 * MFRC522 device: Generic, authentic MFRC522 version 0x92 / 2.0
  
### Step 2: Describe the problem
Board correctly returns version 2.0 using the firmware dump but fails to read any tags, in any of the examples.
My tags have been shipped together with the reader and confirmed to be MIFARE classic tags using my mobile phone.

#### Observed Results:

  * Dumpinfo example does not return anything / is waiting for a card.
  
#### Expected Results:

  * Info of my card (contact info to be dumped)

**Comment by vladko312** [comment]
README file has no pinout for this exact board. What pins were you using for the signals?

**Comment by Rotzbua** [comment]
If the example returns a version the wiring should be correct. @syntaxbullet Do you use own code or a specific example?

**Comment by syntaxbullet** [comment]
seems like my supplier provided me with some rfid scanners that didn't work, even though the package was new and unopened, ordering a new batch fixed the issue. Thank you for your responses ;)
