### ISSUE TITLE
PICC type: Unknown type

### ISSUE THREAD

**Issue by zgluis** [miguelbalboa/rfid#596]
### Step 1: Describe your environment

 * OS version: MacOS
 * Arduino IDE version: 2.0.3
 * MFRC522 Library version: 1.4.10
 * Arduino device: Uno
 * MFRC522 device:  0x92 = v2.0
  
### Step 2: Describe the problem

I'm trying to use the `DumpInfo` example with my elevator card but terminal always outputs

```
Card UID: A3 AC 6D 9A
Card SAK: 19
PICC type: Unknown type
```

Should I try with a different code version? What could be the possibles reasons for this error code?

**Comment by Rotzbua** [comment]
> Should I try with a different code version?

Yes why not?

> What could be the possibles reasons for this error code?

Card too new or other vendor. As alternative use NXP app from google store on your phone.
