### ISSUE TITLE
RC522

### ISSUE THREAD

**Issue by c1p81** [miguelbalboa/rfid#6]
i would like to use the rfid reader rc522 with the Ethernet Shield on Arduino but they share the digital pin 11,12 and 13. It's possible to change the rfid reader pins in your library (maybe changing PCD_TRANSCEIVE and others)????
thank you

Luca Innocenti from Italy

**Comment by sandeepthakur10** [comment]
I am having the same problem.
I am using ARDUINO UNO + ETHERNET SHIELD + RFID R522
I am not able to change the reset and ss pin of RFID.
Can you please help me. I am using rfid example code from arduino example and cannt find where to the ss and rest pin in code.
Kindly suggest me a way.
