### ISSUE TITLE
Considering F()ing your strings.

### ISSUE THREAD

**Issue by awyork** [miguelbalboa/rfid#62]
You may want to F() your strings.  

https://learn.adafruit.com/memories-of-an-arduino/optimizing-sram

This will cut the dynamic memory usage of the ReadAndWrite demo in half.  There are places in the cpp file where this can be done too.

Thanks.

**Comment by miguelbalboa** [comment]
At 5b148a2e7245acb2b1f0454026992e3b9dd9b0d7 by @lorneb

**Comment by lorneb** [comment]
Yes that is what my change set did
