### ISSUE TITLE
Read write code not working

### ISSUE THREAD

**Issue by RitikaMalik** [miguelbalboa/rfid#67]
I uploaded this code on my arduino uno. But it does not seem to work. I am getting a NACK from the PICC. What changes should I do?

**Comment by omersiar** [comment]
Which code did you upload? Do you have another PICC?

**Comment by RitikaMalik** [comment]
I uploaded the Read/Write Code that is a part of the attached examples file. Yes, I do have 2 PICCs. I am facing the same problem in both. 
One more thing, I looked into the .c file of the MFRC522 library where I stumbled upon a function called "DumpMifareClassicSectorToSerial". This function works fine and it internally calls MIFARE_Read(). This means that the read function is also but the way in which has been called in that Read/Write code is wrong.
Am I thinking in the right direction?
Thanks for the help.

**Comment by omersiar** [comment]
Reading/Writing requires Authentication which is not always done by Library examples default (different keys). You need to modify for your needs.

**Comment by RitikaMalik** [comment]
I do agree to the authentication part. But if the authentication is working fine in "DumpMifareClassicSectorToSerial", then why does it fail in the example code?

**Comment by RitikaMalik** [comment]
And I will go through the functions once again, may be I lack some basic understanding of the same.
Thanks.

**Comment by mdxs** [comment]
@RitikaMalik : Is this still an issue for you?  Otherwise, please report back so that this issue can be closed. In general I would suggest to first run the DumpInfo example before trying ReadAndWrite (and note that ReadAndWrite will attempt to change data... which, as @omersiar said may require authentication).

**Comment by RitikaMalik** [comment]
No, this is no more an issue for me. :)

On Mon, Mar 16, 2015 at 6:33 PM, mdxs <notifications@github.com> wrote:

> @RitikaMalik <https://github.com/RitikaMalik> : Is this still an issue
> for you? Otherwise, please report back so that this issue can be closed. In
> general I would suggest to first run the DumpInfo example before trying
> ReadAndWrite (and note that ReadAndWrite will attempt to change data...
> which, as @omersiar <https://github.com/omersiar> said may require
> authentication).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miguelbalboa/rfid/issues/67#issuecomment-81647466>.
>



-- 
Ritika Malik
Undergraduate, Final year
Electronics and Communication Engineering
Netaji Subhas Institute of Technology
University of Delhi
Sector-3, Dwarka, New Delhi-110078

**Comment by gnrcampos** [comment]
I think I am having an authentication issue here, how am I supposed to know the authentication key for my tags and cards?

**Comment by mdxs** [comment]
I think this issue should be closed.

@gnrcampos When you use authentication on your own (originally) blank tags/cards, you should remember it yourself. When that fails, on blank tags/cards, perhaps the "rfid_default_kes" in examples (and the link in the comments) can help you. When you try to access tags/cards that are controlled by others (like public library, transportation, bank, etc.)... then you are perhaps not supposed to know the authentication keys ;-)
