### ISSUE TITLE
MifareRead changes buffer size also if not STATUS_OK

### ISSUE THREAD

**Issue by purehunter** [miguelbalboa/rfid#85]
byte MFRC522::MIFARE_Read(	byte blockAddr, 	///< MIFARE Classic: The block (0-0xff) number. MIFARE Ultralight: The first page to return data from.
							byte *buffer,		///< The buffer to store the data in
							byte *bufferSize	///< Buffer size, at least 18 bytes. Also number of bytes returned if STATUS_OK.

The bufferSize will also be changed, if a CRC error occurs during reading. Then the bufferSize is changed to the number of correctly read bytes.

**Comment by mdxs** [comment]
Don't understand if you see it as a problem or as a feature... are you suggesting this needs to be fixed (based on specification / expectation) or to change the function documentation?
