### ISSUE TITLE
Not working with pro micro

### ISSUE THREAD

**Issue by pashaj11** [miguelbalboa/rfid#94]
I have tested the examples with Arduino Uno. However, with the Adafruit Pro micro nothing works. Everything hangs on the call mfrc522.PICC_ReadCardSerial (). The description says that Pro micro pin RESET must be connected to the RST reader. As in this case, the sketch correctly identify the pins instead of #define RST_PIN 9? Thanks in advance for your reply.

**Comment by Rotzbua** [comment]
@pashaj11 Hi. Did you found a solution? Or a more detailed bug description?
Otherwise I will close this issue.

**Comment by bernardo-inithaus** [comment]
Try defining the RST_PIN as the pin number 13. It worked for me.
