### ISSUE TITLE
Arduino Leonardo Support?

### ISSUE THREAD

**Issue by kelna2** [miguelbalboa/rfid#97]
Is there support for the Arduino Leonardo? I wired it up according to the Pin Layout chart using the ICSP pins but I haven't been able to get it talk over serial. I added a while loop (which is standard for Leonardos) to beginning of the Dump example but I'm not seeing anything printed to the serial monitor, even when I reset the Leonardo.

void setup() {
	Serial.begin(9600); 
          while (!Serial) {
          ; // wait for serial port to connect. Needed for Leonardo only
         }
	SPI.begin();			// Init SPI bus
	mfrc522.PCD_Init();		// Init MFRC522
	ShowReaderDetails();	// Show details of PCD - MFRC522 Card Reader details
	Serial.println("Scan PICC to see UID, type, and data blocks...");
}

Any suggestions on how to get it the Leonardo to talk to the RFID reader?

Thanks!
-Ben

**Comment by ricardojlrufino** [comment]
Its working, see my code
I'm using ICSP header

```
//Programa : RFID - Controle de Acesso leitor RFID
//Autor : FILIPEFLOP
 
#include <SPI.h>
#include <MFRC522.h>
 
#define SS_PIN 10
#define RST_PIN 9
MFRC522 mfrc522(SS_PIN, RST_PIN);   // Create MFRC522 instance.
 

char st[20];
 
void setup() 
{
  Serial.begin(9600);   // Inicia a serial
  SPI.begin();      // Inicia  SPI bus
  mfrc522.PCD_Init();   // Inicia MFRC522
  while(! Serial) {}
  Serial.println("Aproxime o seu cartao do leitor...");
  Serial.println();
}
 
void loop() 
{
  // Look for new cards
  if ( ! mfrc522.PICC_IsNewCardPresent()) 
  {
    return;
  }
  // Select one of the cards
  if ( ! mfrc522.PICC_ReadCardSerial()) 
  {
    return;
  }
  //Mostra UID na serial
  Serial.print("UID da tag - [");
  Serial.print(mfrc522.uid.size);
  Serial.print("] :");
  for (byte i = 0; i < mfrc522.uid.size; i++) 
  {
     Serial.print(mfrc522.uid.uidByte[i] < 0x10 ? " 0" : " ");
     Serial.print(mfrc522.uid.uidByte[i], HEX);
     
  }
  Serial.println();
 
} 
```
